import { makeSeedRule } from "@/registry/seed/shared";

export const aiGovernanceRules = [
  makeSeedRule({
    stable_id: "REG-AI-001",
    title: "AI Act — Prohibited Practices and AI Literacy",
    short_label: "AI Act Phase 1",
    legal_family: "ai_governance",
    jurisdiction: "EU",
    jurisdiction_level: "EU",
    framework_group: ["MN", "L", "O", "AGRI"],
    sources: [
      {
        label: "Framework regulation",
        source_family: "EUR-Lex" as const,
        reference: "Regulation (EU) 2024/1689, Chapters I-II (Art. 1-5)",
        official_url: "https://eur-lex.europa.eu/eli/reg/2024/1689/oj",
        oj_reference: "OJ L, 2024/1689, 12 July 2024",
        authoritative_reference: "CELEX:32024R1689",
        last_verified_on: "2026-04-17",
      },
    ],
    lifecycle_state: "ACTIVE",
    trigger_logic: {
      mode: "declarative",
      match_mode: "all",
      conditions: [{ field: "hasAI", operator: "is_true", value: true }],
      fallback_if_missing: "not_applicable",
    },
    temporal: {
      entry_into_force: "2024-08-01",
      applies_to_new_types_from: null,
      applies_to_all_new_vehicles_from: null,
      applies_to_first_registration_from: null,
      applies_from_generic: "2025-02-02",
      effective_to: null,
      small_volume_derogation_until: null,
      notes: null,
    },
    obligation_text:
      "Prohibited AI practices must not be deployed and AI literacy obligations apply to providers and deployers of AI systems.",
    owner_hint: "ai_governance",
    ui_package: "horizontal",
    process_stage: "pre_ta",
  }),
  makeSeedRule({
    stable_id: "REG-AI-002",
    title: "AI Act — General-Purpose AI Model Obligations",
    short_label: "AI Act GPAI",
    legal_family: "ai_governance",
    jurisdiction: "EU",
    jurisdiction_level: "EU",
    framework_group: ["MN", "L", "O", "AGRI"],
    sources: [
      {
        label: "Framework regulation",
        source_family: "EUR-Lex" as const,
        reference: "Regulation (EU) 2024/1689, Chapter V (Art. 51-56, GPAI)",
        official_url: "https://eur-lex.europa.eu/eli/reg/2024/1689/oj",
        oj_reference: "OJ L, 2024/1689, 12 July 2024",
        authoritative_reference: "CELEX:32024R1689",
        last_verified_on: "2026-04-17",
      },
    ],
    lifecycle_state: "ACTIVE",
    promoted_on: "2026-04-17",
    promoted_by: "phase-11b2-batch2",
    trigger_logic: {
      mode: "declarative",
      match_mode: "all",
      conditions: [{ field: "aiLevel", operator: "eq", value: "foundation_model" }],
      fallback_if_missing: "not_applicable",
    },
    temporal: {
      entry_into_force: "2024-08-01",
      applies_to_new_types_from: null,
      applies_to_all_new_vehicles_from: null,
      applies_to_first_registration_from: null,
      applies_from_generic: "2025-08-02",
      effective_to: null,
      small_volume_derogation_until: null,
      notes:
        "GPAI obligations apply from 2 August 2025. Applicability depends on whether the OEM acts as a GPAI provider (designs/trains a general-purpose model) or only as a deployer.",
    },
    obligation_text:
      "Providers of GPAI models must maintain technical documentation (Art. 53), respect EU copyright law, publish training-data summaries, and — for systemic-risk models — perform model evaluations and report serious incidents (Art. 55).",
    owner_hint: "ai_governance",
    ui_package: "horizontal",
    process_stage: "pre_ta",
  }),
  makeSeedRule({
    stable_id: "REG-AI-003",
    title: "AI Act — High-Risk AI Systems (Annex III)",
    short_label: "AI Act Annex III",
    legal_family: "ai_governance",
    jurisdiction: "EU",
    jurisdiction_level: "EU",
    framework_group: ["MN", "L", "O", "AGRI"],
    sources: [
      {
        label: "Framework regulation",
        source_family: "EUR-Lex" as const,
        reference: "Regulation (EU) 2024/1689, Art. 6(2) and Annex III",
        official_url: "https://eur-lex.europa.eu/eli/reg/2024/1689/oj",
        oj_reference: "OJ L, 2024/1689, 12 July 2024",
        authoritative_reference: "CELEX:32024R1689",
        last_verified_on: "2026-04-17",
      },
    ],
    lifecycle_state: "ACTIVE",
    promoted_on: "2026-04-17",
    promoted_by: "phase-11b2-batch2",
    trigger_logic: {
      mode: "declarative",
      match_mode: "any",
      conditions: [
        {
          field: "dataFlags",
          operator: "includes",
          value: "cabin_camera",
          label: "Biometric processing",
        },
        {
          field: "dataFlags",
          operator: "includes",
          value: "driver_profiling",
          label: "Driver profiling",
        },
      ],
      fallback_if_missing: "unknown",
      conditional_reason:
        "Vehicle may contain Annex III high-risk AI — classification review required.",
    },
    temporal: {
      entry_into_force: "2024-08-01",
      applies_to_new_types_from: null,
      applies_to_all_new_vehicles_from: null,
      applies_to_first_registration_from: null,
      applies_from_generic: "2026-08-02",
      effective_to: null,
      small_volume_derogation_until: null,
      notes:
        "Annex III standalone high-risk categories apply from 2 August 2026. Category mapping to in-vehicle AI (e.g. biometric categorisation, employment/worker-management contexts) still requires case-by-case review.",
    },
    obligation_text:
      "Annex III high-risk AI systems (e.g. biometric categorisation, emotion recognition in certain contexts) must meet conformity assessment, technical documentation (Art. 11), risk-management (Art. 9), logging (Art. 12), and post-market monitoring (Art. 72) requirements from 2 August 2026.",
    owner_hint: "ai_governance",
    ui_package: "horizontal",
    process_stage: "pre_ta",
  }),
  makeSeedRule({
    stable_id: "REG-AI-004",
    title: "AI Act — Safety Components in Regulated Products",
    short_label: "AI Act Art. 6(1) Automotive",
    legal_family: "ai_governance",
    jurisdiction: "EU",
    jurisdiction_level: "EU",
    framework_group: ["MN", "L", "O", "AGRI"],
    sources: [
      {
        label: "Framework regulation",
        source_family: "EUR-Lex" as const,
        reference: "Regulation (EU) 2024/1689, Art. 6(1) and Annex I Section B",
        official_url: "https://eur-lex.europa.eu/eli/reg/2024/1689/oj",
        oj_reference: "OJ L, 2024/1689, 12 July 2024",
        authoritative_reference: "CELEX:32024R1689",
        last_verified_on: "2026-04-17",
      },
    ],
    lifecycle_state: "ACTIVE",
    trigger_logic: {
      mode: "declarative",
      match_mode: "all",
      conditions: [
        {
          field: "hasSafetyRelevantAI",
          operator: "is_true",
          value: true,
          label: "Vehicle uses AI as a safety component",
        },
      ],
      fallback_if_missing: "not_applicable",
    },
    temporal: {
      entry_into_force: "2024-08-01",
      applies_to_new_types_from: null,
      applies_to_all_new_vehicles_from: null,
      applies_to_first_registration_from: null,
      applies_from_generic: "2027-08-02",
      effective_to: null,
      small_volume_derogation_until: null,
      notes:
        "Interaction between AI Act conformity assessment and vehicle type-approval remains under review.",
    },
    obligation_text:
      "AI systems used as safety components in vehicles are classified as high-risk under Art. 6(1).",
    evidence_tasks: [
      "AI system inventory",
      "Risk classification per Art. 6(1)/Annex I",
      "Conformity assessment documentation",
      "Technical documentation per Art. 11",
      "Quality management system",
      "Post-market monitoring plan",
    ],
    owner_hint: "ai_governance",
    planning_lead_time_months: 24,
    ui_package: "horizontal",
    process_stage: "pre_ta",
    prerequisite_standards: [
      "ISO/PAS 8800:2024 (Road vehicles — Safety and artificial intelligence)",
      "ISO 26262 (functional safety — when AI is part of a safety function)",
      "ISO 21448 (SOTIF — intended functionality under learned behaviour)",
    ],
  }),
];
