import { makeSeedRule, makeSource } from "@/registry/seed/shared";

export const dataAccessRules = [
  makeSeedRule({
    stable_id: "REG-DA-001",
    title: "EU Data Act",
    short_label: "Data Act",
    legal_family: "data_access",
    jurisdiction: "EU",
    jurisdiction_level: "EU",
    framework_group: ["MN", "L", "O", "AGRI"],
    sources: [
      makeSource(
        "Framework regulation",
        "EUR-Lex",
        "Regulation (EU) 2023/2854",
        "OJ L, 2023/2854, 22 December 2023",
      ),
    ],
    lifecycle_state: "ACTIVE",
    trigger_logic: {
      mode: "declarative",
      match_mode: "all",
      conditions: [{ field: "hasConnectedServices", operator: "is_true", value: true }],
      fallback_if_missing: "not_applicable",
    },
    temporal: {
      entry_into_force: "2024-01-11",
      applies_to_new_types_from: null,
      applies_to_all_new_vehicles_from: null,
      applies_to_first_registration_from: null,
      applies_from_generic: "2025-09-12",
      effective_to: null,
      small_volume_derogation_until: null,
      notes: null,
    },
    obligation_text:
      "Users of connected products must be able to access data generated by their vehicle in a structured, machine-readable format.",
    owner_hint: "connected_services",
    planning_lead_time_months: 18,
    ui_package: "horizontal",
    process_stage: "post_market",
  }),
];
