import { makeSeedRule, makeSource } from "@/registry/seed/shared";

export const emissionsCo2Rules = [
  makeSeedRule({
    stable_id: "REG-EM-001",
    title: "Euro 7 Emission Standard — Light-Duty Vehicles",
    short_label: "Euro 7 (M1/N1)",
    legal_family: "emissions_co2",
    jurisdiction: "EU",
    jurisdiction_level: "EU",
    framework_group: ["MN"],
    sources: [
      {
        label: "Framework regulation",
        source_family: "EUR-Lex" as const,
        reference: "Regulation (EU) 2024/1257",
        official_url: "https://eur-lex.europa.eu/eli/reg/2024/1257/oj",
        oj_reference: "OJ L, 2024/1257, 8 May 2024",
        authoritative_reference: "CELEX:32024R1257",
        last_verified_on: "2026-04-17",
      },
      {
        label: "Implementing regulation (exhaust/evaporative)",
        source_family: "Commission legal act" as const,
        reference: "Implementing Regulation (EU) 2025/1706",
        official_url: "https://eur-lex.europa.eu/eli/reg_impl/2025/1706/oj",
        oj_reference: "OJ L, 2025/1706, 5 September 2025",
        authoritative_reference: "CELEX:32025R1706",
        last_verified_on: "2026-04-17",
      },
      {
        label: "Implementing regulation (OBFCM/OBM/EVP)",
        source_family: "Commission legal act" as const,
        reference: "Implementing Regulation (EU) 2025/1707",
        official_url: "https://eur-lex.europa.eu/eli/reg_impl/2025/1707/oj",
        oj_reference: "OJ L, 2025/1707, 5 September 2025",
        authoritative_reference: "CELEX:32025R1707",
        last_verified_on: "2026-04-17",
      },
    ],
    lifecycle_state: "ACTIVE",
    promoted_on: "2026-04-17",
    promoted_by: "phase-11b2-batch2",
    trigger_logic: {
      mode: "declarative",
      match_mode: "all",
      conditions: [
        { field: "frameworkGroup", operator: "eq", value: "MN" },
        { field: "vehicleCategory", operator: "in", value: ["M1", "N1"] },
      ],
      fallback_if_missing: "unknown",
    },
    temporal: {
      entry_into_force: "2024-05-28",
      applies_to_new_types_from: "2026-11-29",
      applies_to_all_new_vehicles_from: "2027-11-29",
      applies_to_first_registration_from: null,
      applies_from_generic: null,
      effective_to: null,
      small_volume_derogation_until: "2030-07-01",
      notes:
        "2025/1707 primarily covers M1/N1 with relevant extension logic for designated N2 cases.",
    },
    obligation_text:
      "M1/N1 vehicles must comply with Euro 7 emission limits, OBM, OBFCM, EVP, and battery durability requirements where relevant.",
    evidence_tasks: [
      "Euro 7 type-approval application",
      "Exhaust emission test reports",
      "OBM system compliance",
      "OBFCM device compliance",
      "EVP generation",
      "Battery durability documentation",
    ],
    owner_hint: "powertrain_emissions",
    planning_lead_time_months: 24,
    ui_package: "wvta_core",
    process_stage: "type_approval",
  }),
  makeSeedRule({
    stable_id: "REG-EM-002",
    title: "Euro 7 Emission Standard — Heavy-Duty Vehicles",
    short_label: "Euro 7 (HD)",
    legal_family: "emissions_co2",
    jurisdiction: "EU",
    jurisdiction_level: "EU",
    framework_group: ["MN"],
    sources: [
      {
        label: "Framework regulation",
        source_family: "EUR-Lex" as const,
        reference: "Regulation (EU) 2024/1257, heavy-duty Annex (Table 2 of Annex I)",
        official_url: "https://eur-lex.europa.eu/eli/reg/2024/1257/oj",
        oj_reference: "OJ L, 2024/1257, 8 May 2024",
        authoritative_reference: "CELEX:32024R1257",
        last_verified_on: "2026-04-17",
      },
    ],
    lifecycle_state: "ACTIVE",
    promoted_on: "2026-04-17",
    promoted_by: "phase-11b2-batch2",
    trigger_logic: {
      mode: "declarative",
      match_mode: "all",
      conditions: [
        { field: "frameworkGroup", operator: "eq", value: "MN" },
        { field: "vehicleCategory", operator: "in", value: ["M2", "M3", "N2", "N3"] },
      ],
      fallback_if_missing: "unknown",
    },
    temporal: {
      entry_into_force: "2024-05-28",
      applies_to_new_types_from: "2028-05-29",
      applies_to_all_new_vehicles_from: "2029-05-29",
      applies_to_first_registration_from: null,
      applies_from_generic: null,
      effective_to: null,
      small_volume_derogation_until: "2031-07-01",
      notes:
        "Framework dates fixed by 2024/1257 for M2/M3/N2/N3. Heavy-duty implementing acts (test procedures, OBM/OBFCM details) are still being adopted — monitor 2026–2027 for technical supplements.",
    },
    obligation_text:
      "M2/M3/N2/N3 vehicles must comply with Euro 7 framework emission limits (including reduced NOx 230 mg/kWh, new N2O/NH3 limits, and broader durability ranges) from the phase-in dates in Regulation (EU) 2024/1257.",
    evidence_tasks: [
      "Heavy-duty Euro 7 type-approval strategy",
      "Emission-durability test plan (up to 700,000 km)",
      "OBM/OBFCM heavy-duty design plan (subject to forthcoming implementing acts)",
    ],
    owner_hint: "powertrain_emissions",
    planning_lead_time_months: 36,
    ui_package: "wvta_core",
    process_stage: "type_approval",
  }),
  makeSeedRule({
    stable_id: "REG-EM-003",
    title: "CO2 Fleet Targets (Cars/Vans)",
    short_label: "CO2 Fleet Targets",
    legal_family: "emissions_co2",
    jurisdiction: "EU",
    jurisdiction_level: "EU",
    framework_group: ["MN"],
    sources: [
      {
        label: "Framework regulation",
        source_family: "EUR-Lex" as const,
        reference: "Regulation (EU) 2019/631 setting CO2 performance standards for new passenger cars and light commercial vehicles",
        official_url: "https://eur-lex.europa.eu/eli/reg/2019/631/oj",
        oj_reference: "OJ L 111, 25.4.2019, p. 13",
        authoritative_reference: "CELEX:32019R0631",
        last_verified_on: "2026-04-17",
      },
      {
        label: "2023 amendment (CO2 targets 2030/2035)",
        source_family: "EUR-Lex" as const,
        reference: "Regulation (EU) 2023/851 amending 2019/631",
        official_url: "https://eur-lex.europa.eu/eli/reg/2023/851/oj",
        oj_reference: "OJ L 110, 25.4.2023, p. 5",
        authoritative_reference: "CELEX:32023R0851",
        last_verified_on: "2026-04-17",
      },
    ],
    lifecycle_state: "ACTIVE",
    promoted_on: "2026-04-17",
    promoted_by: "phase-11b2-batch2",
    trigger_logic: {
      mode: "declarative",
      match_mode: "all",
      conditions: [
        { field: "frameworkGroup", operator: "eq", value: "MN" },
        { field: "vehicleCategory", operator: "in", value: ["M1", "N1"] },
      ],
      fallback_if_missing: "unknown",
    },
    temporal: {
      entry_into_force: "2019-05-15",
      applies_to_new_types_from: null,
      applies_to_all_new_vehicles_from: null,
      applies_to_first_registration_from: null,
      applies_from_generic: "2020-01-01",
      effective_to: null,
      small_volume_derogation_until: null,
      notes:
        "Fleet CO2 targets phase in: 2020 (baseline), 2025 (−15%), 2030 (−55% cars / −50% vans), 2035 (−100%). Targets are calculated at manufacturer-fleet level; individual vehicles contribute to the fleet average.",
    },
    obligation_text:
      "Manufacturers must not exceed specific CO2 emission targets calculated over their EU fleet of newly registered M1 and N1 vehicles for each calendar year. Missing the target triggers an excess-emissions premium of EUR 95/gCO2/km per vehicle registered.",
    evidence_tasks: [
      "Fleet CO2 planning model per calendar year",
      "Pooling agreement (if applicable)",
      "Annual fleet CO2 reporting to EEA",
      "Eco-innovation credits documentation",
    ],
    owner_hint: "powertrain_emissions",
    planning_lead_time_months: 24,
    ui_package: "horizontal",
    process_stage: "post_market",
  }),
  makeSeedRule({
    stable_id: "REG-EM-004",
    title: "WLTP — Worldwide Harmonized Light Vehicle Test Procedure",
    short_label: "WLTP",
    legal_family: "emissions_co2",
    jurisdiction: "EU",
    jurisdiction_level: "EU",
    framework_group: ["MN"],
    sources: [
      makeSource(
        "Framework regulation",
        "EUR-Lex",
        "Commission Regulation (EU) 2017/1151 (WLTP implementing measures)",
        "OJ L 175, 7.7.2017",
      ),
    ],
    lifecycle_state: "SEED_UNVERIFIED",
    trigger_logic: {
      mode: "declarative",
      match_mode: "all",
      conditions: [
        { field: "frameworkGroup", operator: "eq", value: "MN" },
        { field: "vehicleCategory", operator: "in", value: ["M1", "N1"] },
      ],
      fallback_if_missing: "unknown",
    },
    obligation_text:
      "Type-approval emissions and fuel consumption values must be determined using the WLTP procedure. WLTP values are used for CO2 fleet targets, labelling, and taxation.",
    owner_hint: "powertrain_emissions",
    ui_package: "wvta_core",
    process_stage: "type_approval",
  }),
  makeSeedRule({
    stable_id: "REG-EM-005",
    title: "Real Driving Emissions (RDE)",
    short_label: "RDE",
    legal_family: "emissions_co2",
    jurisdiction: "EU",
    jurisdiction_level: "EU",
    framework_group: ["MN"],
    sources: [
      makeSource(
        "Framework regulation",
        "EUR-Lex",
        "Commission Regulation (EU) 2016/427 and amendments (RDE packages 1-4)",
      ),
    ],
    lifecycle_state: "SEED_UNVERIFIED",
    trigger_logic: {
      mode: "declarative",
      match_mode: "all",
      conditions: [
        { field: "frameworkGroup", operator: "eq", value: "MN" },
        { field: "vehicleCategory", operator: "in", value: ["M1", "N1", "M2", "N2"] },
      ],
      fallback_if_missing: "unknown",
    },
    obligation_text:
      "Vehicles must demonstrate compliance with emission limits under real driving conditions using portable emission measurement systems (PEMS).",
    owner_hint: "powertrain_emissions",
    ui_package: "wvta_core",
    process_stage: "type_approval",
  }),
];
