import { makeSeedRule, makeSource } from "@/registry/seed/shared";

export const emissionsCo2Rules = [
  makeSeedRule({
    stable_id: "REG-EM-001",
    title: "Euro 7 Emission Standard — Light-Duty Vehicles",
    short_label: "Euro 7 (M1/N1)",
    legal_family: "emissions_co2",
    jurisdiction: "EU",
    jurisdiction_level: "EU",
    framework_group: ["MN"],
    sources: [
      {
        label: "Framework regulation",
        source_family: "EUR-Lex" as const,
        reference: "Regulation (EU) 2024/1257",
        official_url: "https://eur-lex.europa.eu/eli/reg/2024/1257/oj",
        oj_reference: "OJ L, 2024/1257, 8 May 2024",
        authoritative_reference: "CELEX:32024R1257",
        last_verified_on: "2026-04-19",
      },
      {
        label: "Implementing regulation (exhaust/evaporative)",
        source_family: "Commission legal act" as const,
        reference: "Implementing Regulation (EU) 2025/1706",
        official_url: "https://eur-lex.europa.eu/eli/reg_impl/2025/1706/oj",
        oj_reference: "OJ L, 2025/1706, 5 September 2025",
        authoritative_reference: "CELEX:32025R1706",
        last_verified_on: "2026-04-19",
      },
      {
        label: "Implementing regulation (OBFCM/OBM/EVP)",
        source_family: "Commission legal act" as const,
        reference: "Implementing Regulation (EU) 2025/1707",
        official_url: "https://eur-lex.europa.eu/eli/reg_impl/2025/1707/oj",
        oj_reference: "OJ L, 2025/1707, 5 September 2025",
        authoritative_reference: "CELEX:32025R1707",
        last_verified_on: "2026-04-19",
      },
    ],
    lifecycle_state: "ACTIVE",
    promoted_on: "2026-04-17",
    promoted_by: "phase-11b2-batch2",
    trigger_logic: {
      // Sprint 6: added human labels. Kept the category precision
      // (M1/N1 only); heavy-duty Euro 7 is REG-EM-002. Without the
      // category condition, an M3 bus pilot would falsely inherit
      // light-duty emission requirements.
      mode: "declarative",
      match_mode: "all",
      conditions: [
        {
          field: "frameworkGroup",
          operator: "eq",
          value: "MN",
          label: "Framework group is MN",
        },
        {
          field: "vehicleCategory",
          operator: "in",
          value: ["M1", "N1"],
          label: "Vehicle category is M1 or N1 (light-duty)",
        },
      ],
      fallback_if_missing: "unknown",
    },
    temporal: {
      entry_into_force: "2024-05-28",
      applies_to_new_types_from: "2026-11-29",
      applies_to_all_new_vehicles_from: "2027-11-29",
      applies_to_first_registration_from: null,
      applies_from_generic: null,
      effective_to: null,
      small_volume_derogation_until: "2030-07-01",
      notes:
        "2025/1707 primarily covers M1/N1 with relevant extension logic for designated N2 cases.",
    },
    obligation_text:
      "Euro 7 framework applies to all M1/N1 light-duty vehicles regardless of powertrain, but individual obligations vary: combustion vehicles must meet exhaust PN10/NOx/HC/CO limits, EVAP + OBM + OBFCM (see REG-EM-013); battery electric, hybrid, and plug-in hybrid vehicles with traction batteries must meet battery durability standards (see REG-EM-014); all M1/N1 regardless of powertrain are subject to non-exhaust emissions monitoring (tyre wear + brake particulate from 2028) and the Environmental Vehicle Passport (EVP).",
    evidence_tasks: [
      "Euro 7 framework type-approval application (M1/N1)",
      "Environmental Vehicle Passport (EVP) data structure",
      "Non-exhaust emissions monitoring plan (tyre + brake particulate, from 2028)",
      "Powertrain-specific evidence tracked in REG-EM-013 (combustion) / REG-EM-014 (battery durability)",
    ],
    owner_hint: "powertrain_emissions",
    planning_lead_time_months: 24,
    ui_package: "wvta_core",
    process_stage: "type_approval",
    content_provenance: {
      source_type: "eur_lex",
      retrieved_at: "2026-04-19",
      human_reviewer: "yanhao",
    },
    related_rules: [
      { rule_id: "REG-EM-013", relation: "complements" },
      { rule_id: "REG-EM-014", relation: "complements" },
    ],
  }),
  makeSeedRule({
    stable_id: "REG-EM-002",
    title: "Euro 7 Emission Standard — Heavy-Duty Vehicles",
    short_label: "Euro 7 (HD)",
    legal_family: "emissions_co2",
    jurisdiction: "EU",
    jurisdiction_level: "EU",
    framework_group: ["MN"],
    sources: [
      {
        label: "Framework regulation",
        source_family: "EUR-Lex" as const,
        reference: "Regulation (EU) 2024/1257, heavy-duty Annex (Table 2 of Annex I)",
        official_url: "https://eur-lex.europa.eu/eli/reg/2024/1257/oj",
        oj_reference: "OJ L, 2024/1257, 8 May 2024",
        authoritative_reference: "CELEX:32024R1257",
        last_verified_on: "2026-04-17",
      },
    ],
    lifecycle_state: "ACTIVE",
    promoted_on: "2026-04-17",
    promoted_by: "phase-11b2-batch2",
    trigger_logic: {
      mode: "declarative",
      match_mode: "all",
      conditions: [
        { field: "frameworkGroup", operator: "eq", value: "MN" },
        { field: "vehicleCategory", operator: "in", value: ["M2", "M3", "N2", "N3"] },
      ],
      fallback_if_missing: "unknown",
    },
    temporal: {
      entry_into_force: "2024-05-28",
      applies_to_new_types_from: "2028-05-29",
      applies_to_all_new_vehicles_from: "2029-05-29",
      applies_to_first_registration_from: null,
      applies_from_generic: null,
      effective_to: null,
      small_volume_derogation_until: "2031-07-01",
      notes:
        "Framework dates fixed by 2024/1257 for M2/M3/N2/N3. Heavy-duty implementing acts (test procedures, OBM/OBFCM details) are still being adopted — monitor 2026–2027 for technical supplements.",
    },
    obligation_text:
      "M2/M3/N2/N3 vehicles must comply with Euro 7 framework emission limits (including reduced NOx 230 mg/kWh, new N2O/NH3 limits, and broader durability ranges) from the phase-in dates in Regulation (EU) 2024/1257.",
    evidence_tasks: [
      "Heavy-duty Euro 7 type-approval strategy",
      "Emission-durability test plan (up to 700,000 km)",
      "OBM/OBFCM heavy-duty design plan (subject to forthcoming implementing acts)",
    ],
    owner_hint: "powertrain_emissions",
    planning_lead_time_months: 36,
    ui_package: "wvta_core",
    process_stage: "type_approval",
  }),
  makeSeedRule({
    stable_id: "REG-EM-003",
    title: "CO2 Fleet Targets (Cars/Vans)",
    short_label: "CO2 Fleet Targets",
    legal_family: "emissions_co2",
    jurisdiction: "EU",
    jurisdiction_level: "EU",
    framework_group: ["MN"],
    sources: [
      {
        label: "Framework regulation",
        source_family: "EUR-Lex" as const,
        reference: "Regulation (EU) 2019/631 setting CO2 performance standards for new passenger cars and light commercial vehicles",
        official_url: "https://eur-lex.europa.eu/eli/reg/2019/631/oj",
        oj_reference: "OJ L 111, 25.4.2019, p. 13",
        authoritative_reference: "CELEX:32019R0631",
        last_verified_on: "2026-04-17",
      },
      {
        label: "2023 amendment (CO2 targets 2030/2035)",
        source_family: "EUR-Lex" as const,
        reference: "Regulation (EU) 2023/851 amending 2019/631",
        official_url: "https://eur-lex.europa.eu/eli/reg/2023/851/oj",
        oj_reference: "OJ L 110, 25.4.2023, p. 5",
        authoritative_reference: "CELEX:32023R0851",
        last_verified_on: "2026-04-17",
      },
    ],
    lifecycle_state: "ACTIVE",
    promoted_on: "2026-04-17",
    promoted_by: "phase-11b2-batch2",
    trigger_logic: {
      mode: "declarative",
      match_mode: "all",
      conditions: [
        { field: "frameworkGroup", operator: "eq", value: "MN" },
        { field: "vehicleCategory", operator: "in", value: ["M1", "N1"] },
      ],
      fallback_if_missing: "unknown",
    },
    temporal: {
      entry_into_force: "2019-05-15",
      applies_to_new_types_from: null,
      applies_to_all_new_vehicles_from: null,
      applies_to_first_registration_from: null,
      applies_from_generic: "2020-01-01",
      effective_to: null,
      small_volume_derogation_until: null,
      notes:
        "Fleet CO2 targets phase in: 2020 (baseline), 2025 (−15%), 2030 (−55% cars / −50% vans), 2035 (−100%). Targets are calculated at manufacturer-fleet level; individual vehicles contribute to the fleet average.",
    },
    obligation_text:
      "Manufacturers must not exceed specific CO2 emission targets calculated over their EU fleet of newly registered M1 and N1 vehicles for each calendar year. Missing the target triggers an excess-emissions premium of EUR 95/gCO2/km per vehicle registered.",
    evidence_tasks: [
      "Fleet CO2 planning model per calendar year",
      "Pooling agreement (if applicable)",
      "Annual fleet CO2 reporting to EEA",
      "Eco-innovation credits documentation",
    ],
    owner_hint: "powertrain_emissions",
    planning_lead_time_months: 24,
    ui_package: "horizontal",
    process_stage: "post_market",
  }),
  makeSeedRule({
    stable_id: "REG-EM-004",
    title: "WLTP — Worldwide Harmonized Light Vehicle Test Procedure",
    short_label: "WLTP",
    legal_family: "emissions_co2",
    jurisdiction: "EU",
    jurisdiction_level: "EU",
    framework_group: ["MN"],
    sources: [
      makeSource(
        "Framework regulation",
        "EUR-Lex",
        "Commission Regulation (EU) 2017/1151 (WLTP implementing measures)",
        "OJ L 175, 7.7.2017",
      ),
    ],
    lifecycle_state: "SEED_UNVERIFIED",
    trigger_logic: {
      mode: "declarative",
      match_mode: "all",
      conditions: [
        { field: "frameworkGroup", operator: "eq", value: "MN" },
        { field: "vehicleCategory", operator: "in", value: ["M1", "N1"] },
      ],
      fallback_if_missing: "unknown",
    },
    obligation_text:
      "Type-approval emissions and fuel consumption values must be determined using the WLTP procedure. WLTP values are used for CO2 fleet targets, labelling, and taxation.",
    owner_hint: "powertrain_emissions",
    ui_package: "wvta_core",
    process_stage: "type_approval",
  }),
  makeSeedRule({
    stable_id: "REG-EM-005",
    title: "Real Driving Emissions (RDE)",
    short_label: "RDE",
    legal_family: "emissions_co2",
    jurisdiction: "EU",
    jurisdiction_level: "EU",
    framework_group: ["MN"],
    sources: [
      makeSource(
        "Framework regulation",
        "EUR-Lex",
        "Commission Regulation (EU) 2016/427 and amendments (RDE packages 1-4)",
      ),
    ],
    lifecycle_state: "SEED_UNVERIFIED",
    trigger_logic: {
      mode: "declarative",
      match_mode: "all",
      conditions: [
        { field: "frameworkGroup", operator: "eq", value: "MN" },
        { field: "vehicleCategory", operator: "in", value: ["M1", "N1", "M2", "N2"] },
      ],
      fallback_if_missing: "unknown",
    },
    obligation_text:
      "Vehicles must demonstrate compliance with emission limits under real driving conditions using portable emission measurement systems (PEMS).",
    owner_hint: "powertrain_emissions",
    ui_package: "wvta_core",
    process_stage: "type_approval",
  }),

  // Phase I.2 — ICE/PHEV breadth expansion.
  // All rules land SEED_UNVERIFIED pending human source verification; the
  // Euro 6 baseline (006), OBD (007), EVAP (008), PHEV UF (009), AdBlue/SCR
  // (010), CO2 labeling (011), HD VECTO (012), Euro 7 combustion (013) and
  // Euro 7 battery durability (014) collectively distinguish pre-Euro-7
  // ICE paths from Euro 7 via temporal.effective_to short-circuit on 006.
  makeSeedRule({
    stable_id: "REG-EM-006",
    title: "Euro 6 Light-Duty (Legacy Baseline)",
    short_label: "Euro 6 (M1/N1)",
    legal_family: "emissions_co2",
    jurisdiction: "EU",
    jurisdiction_level: "EU",
    framework_group: ["MN"],
    sources: [
      {
        label: "Framework regulation",
        source_family: "EUR-Lex" as const,
        reference: "Regulation (EC) No 715/2007 on type-approval of motor vehicles with respect to emissions from light passenger and commercial vehicles (Euro 5 and Euro 6)",
        official_url: "https://eur-lex.europa.eu/eli/reg/2007/715/oj",
        oj_reference: "OJ L 171, 29.6.2007, p. 1",
        authoritative_reference: "CELEX:32007R0715",
        last_verified_on: "2026-04-21",
      },
      {
        label: "WLTP implementing regulation",
        source_family: "EUR-Lex" as const,
        reference: "Commission Regulation (EU) 2017/1151 (WLTP implementing measures)",
        official_url: "https://eur-lex.europa.eu/eli/reg/2017/1151/oj",
        oj_reference: "OJ L 175, 7.7.2017, p. 1",
        authoritative_reference: "CELEX:32017R1151",
        last_verified_on: "2026-04-21",
      },
      {
        label: "RDE package 4",
        source_family: "EUR-Lex" as const,
        reference: "Commission Regulation (EU) 2018/1832 (RDE package 4)",
        official_url: "https://eur-lex.europa.eu/eli/reg/2018/1832/oj",
        oj_reference: "OJ L 301, 27.11.2018, p. 1",
        authoritative_reference: "CELEX:32018R1832",
        last_verified_on: "2026-04-21",
      },
    ],
    lifecycle_state: "ACTIVE",
    promoted_on: "2026-04-21",
    promoted_by: "phase-j-human-round-2-horizontal",
    trigger_logic: {
      mode: "declarative",
      match_mode: "all",
      conditions: [
        { field: "frameworkGroup", operator: "eq", value: "MN", label: "Framework group is MN" },
        { field: "vehicleCategory", operator: "in", value: ["M1", "N1"], label: "Vehicle category is M1 or N1 (light-duty)" },
        { field: "hasCombustionEngine", operator: "is_true", value: true, label: "Vehicle has a combustion engine" },
      ],
      fallback_if_missing: "not_applicable",
    },
    temporal: {
      entry_into_force: null,
      applies_to_new_types_from: "2014-09-01",
      applies_to_all_new_vehicles_from: "2015-09-01",
      applies_to_first_registration_from: null,
      applies_from_generic: null,
      effective_to: "2026-11-29",
      small_volume_derogation_until: null,
      notes:
        "Euro 6 superseded by Euro 7 (REG-EM-013) for M1/N1 new type-approvals from 2026-11-29 per Reg (EU) 2024/1257.",
    },
    obligation_text:
      "M1/N1 combustion vehicles with SOP before 2026-11-29 must meet Euro 6 limits (CO, HC, NOx, PM, PN) via WLTP + RDE testing, with 5-year / 100,000 km emission-related durability. Superseded by Euro 7 (REG-EM-013) for SOP from 2026-11-29.",
    evidence_tasks: [
      "Euro 6 type-approval certificate",
      "WLTP test report (CO, HC, NOx, PM, PN per WLTC cycle)",
      "RDE conformity-factor report (PEMS on-road testing)",
      "OBD system specification + DTC list",
      "5-year / 100,000 km durability demonstration",
    ],
    owner_hint: "powertrain_emissions",
    ui_package: "wvta_core",
    process_stage: "type_approval",
    content_provenance: {
      source_type: "eur_lex",
      retrieved_at: "2026-04-21",
      human_reviewer: "yanhao",
    },
  }),
  makeSeedRule({
    stable_id: "REG-EM-007",
    title: "On-Board Diagnostics (OBD/EOBD)",
    short_label: "OBD/EOBD",
    legal_family: "emissions_co2",
    jurisdiction: "EU",
    jurisdiction_level: "EU",
    framework_group: ["MN"],
    sources: [
      {
        label: "Original OBD mandate (Dir 98/69/EC)",
        source_family: "EUR-Lex" as const,
        reference: "Directive 98/69/EC on measures to be taken against air pollution by emissions from motor vehicles (original EOBD mandate)",
        official_url: "https://eur-lex.europa.eu/eli/dir/1998/69/oj",
        oj_reference: "OJ L 350, 28.12.1998, p. 1",
        authoritative_reference: "CELEX:31998L0069",
        last_verified_on: "2026-04-21",
      },
      {
        label: "Euro 5/6 integration",
        source_family: "EUR-Lex" as const,
        reference: "Regulation (EC) No 715/2007, Annex XI (OBD requirements)",
        official_url: "https://eur-lex.europa.eu/eli/reg/2007/715/oj",
        oj_reference: "OJ L 171, 29.6.2007, p. 1",
        authoritative_reference: "CELEX:32007R0715",
        last_verified_on: "2026-04-21",
      },
      {
        label: "WLTP-era OBD",
        source_family: "EUR-Lex" as const,
        reference: "Commission Regulation (EU) 2017/1151, Annex XI (OBD for WLTP-era light-duty)",
        official_url: "https://eur-lex.europa.eu/eli/reg/2017/1151/oj",
        oj_reference: "OJ L 175, 7.7.2017, p. 1",
        authoritative_reference: "CELEX:32017R1151",
        last_verified_on: "2026-04-21",
      },
    ],
    lifecycle_state: "ACTIVE",
    promoted_on: "2026-04-21",
    promoted_by: "phase-j-human-round-2-horizontal",
    trigger_logic: {
      mode: "declarative",
      match_mode: "all",
      conditions: [
        { field: "hasCombustionEngine", operator: "is_true", value: true, label: "Vehicle has a combustion engine" },
      ],
      fallback_if_missing: "not_applicable",
    },
    temporal: {
      entry_into_force: null,
      applies_to_new_types_from: null,
      applies_to_all_new_vehicles_from: null,
      applies_to_first_registration_from: null,
      applies_from_generic: "2001-01-01",
      effective_to: null,
      small_volume_derogation_until: null,
      notes:
        "EOBD mandatory for petrol from 2001-01-01, for diesel from 2003-01-01 per Dir 98/69/EC. Integrated into Reg 715/2007 Annex XI + Reg 2017/1151 Annex XI for WLTP-era.",
    },
    obligation_text:
      "Combustion and plug-in-hybrid vehicles must provide on-board diagnostics monitoring emission-related systems: standardized DTCs, physically accessible OBD connector, readiness monitors, ISO 15031 / SAE J1979 scan-tool protocol compliance.",
    evidence_tasks: [
      "OBD system specification",
      "Diagnostic trouble code (DTC) list",
      "Scan-tool conformance report (ISO 15031 / SAE J1979)",
      "Readiness monitor coverage matrix",
      "Dealer diagnostic training package",
    ],
    owner_hint: "powertrain_emissions",
    ui_package: "wvta_core",
    process_stage: "type_approval",
    content_provenance: {
      source_type: "eur_lex",
      retrieved_at: "2026-04-21",
      human_reviewer: "yanhao",
    },
    prerequisite_standards: [
      "ISO 15031 (communication between vehicle and external equipment)",
      "SAE J1979 (OBD-II diagnostic test modes)",
    ],
  }),
  makeSeedRule({
    stable_id: "REG-EM-008",
    title: "Evaporative Emissions (EVAP)",
    short_label: "EVAP",
    legal_family: "emissions_co2",
    jurisdiction: "EU",
    jurisdiction_level: "EU",
    framework_group: ["MN"],
    sources: [
      {
        label: "Euro 5/6 framework (Annex III)",
        source_family: "EUR-Lex" as const,
        reference: "Regulation (EC) No 715/2007, Annex III (evaporative emissions)",
        official_url: "https://eur-lex.europa.eu/eli/reg/2007/715/oj",
        oj_reference: "OJ L 171, 29.6.2007, p. 1",
        authoritative_reference: "CELEX:32007R0715",
        last_verified_on: "2026-04-21",
      },
      {
        label: "Implementing act (Annex VI)",
        source_family: "EUR-Lex" as const,
        reference: "Commission Regulation (EC) No 692/2008, Annex VI (evaporative emissions implementing procedure)",
        official_url: null,
        oj_reference: null,
        authoritative_reference: "CELEX:32008R0692",
        last_verified_on: null,
      },
      {
        label: "WLTP-era SHED (Annex VI)",
        source_family: "EUR-Lex" as const,
        reference: "Commission Regulation (EU) 2017/1151, Annex VI (SHED testing for WLTP-era)",
        official_url: "https://eur-lex.europa.eu/eli/reg/2017/1151/oj",
        oj_reference: "OJ L 175, 7.7.2017, p. 1",
        authoritative_reference: "CELEX:32017R1151",
        last_verified_on: "2026-04-21",
      },
    ],
    lifecycle_state: "ACTIVE",
    promoted_on: "2026-04-21",
    promoted_by: "phase-j-human-round-2-horizontal",
    trigger_logic: {
      mode: "declarative",
      match_mode: "all",
      conditions: [
        { field: "hasFuelTank", operator: "is_true", value: true, label: "Vehicle has a liquid/gaseous fuel tank" },
        { field: "fuelType", operator: "in", value: ["petrol", "lpg", "cng", "lng"], label: "Fuel type is petrol, LPG, CNG or LNG" },
      ],
      fallback_if_missing: "not_applicable",
    },
    temporal: {
      entry_into_force: null,
      applies_to_new_types_from: null,
      applies_to_all_new_vehicles_from: null,
      applies_to_first_registration_from: null,
      applies_from_generic: "2007-07-02",
      effective_to: null,
      small_volume_derogation_until: null,
      notes:
        "Diesel fuel systems are excluded from EVAP due to negligible vapour pressure.",
    },
    obligation_text:
      "Petrol/LPG/CNG/LNG-fueled vehicles must prevent HC vapour escape via charcoal canister + purge valve + leak-detection system, demonstrated by SHED test. Diesel excluded (negligible EVAP).",
    evidence_tasks: [
      "SHED (Sealed Housing for Evaporative Determination) test report",
      "Charcoal canister sizing + activation calculation",
      "Purge valve specification + control strategy",
      "ORVR / leak-detect system documentation",
    ],
    owner_hint: "powertrain_emissions",
    ui_package: "wvta_core",
    process_stage: "type_approval",
    notes: "Diesel fuel systems are excluded from EVAP due to negligible vapor pressure.",
    content_provenance: {
      source_type: "eur_lex",
      retrieved_at: "2026-04-21",
      human_reviewer: "yanhao",
    },
  }),
  makeSeedRule({
    stable_id: "REG-EM-009",
    title: "PHEV CO2 Utility-Factor (R101)",
    short_label: "PHEV UF",
    legal_family: "emissions_co2",
    jurisdiction: "EU",
    jurisdiction_level: "EU",
    framework_group: ["MN"],
    sources: [
      {
        label: "Revised PHEV UF methodology",
        source_family: "EUR-Lex" as const,
        reference: "Commission Regulation (EU) 2023/443 (revised PHEV utility-factor methodology amending WLTP implementing measures)",
        official_url: "https://eur-lex.europa.eu/eli/reg/2023/443/oj",
        oj_reference: "OJ L 66, 2.3.2023 [verify p. 1]",
        authoritative_reference: "CELEX:32023R0443",
        last_verified_on: "2026-04-21",
      },
      {
        label: "UN counterpart — R101",
        source_family: "UNECE" as const,
        reference: "UN Regulation No. 101 (CO2 emissions + fuel consumption — light-duty + PHEV UF methodology)",
        official_url: null,
        oj_reference: null,
        authoritative_reference: null,
        last_verified_on: null,
      },
      {
        label: "Fleet CO2 (Annex I)",
        source_family: "EUR-Lex" as const,
        reference: "Regulation (EU) 2019/631, Annex I (CO2 targets — reference methodology)",
        official_url: "https://eur-lex.europa.eu/eli/reg/2019/631/oj",
        oj_reference: "OJ L 111, 25.4.2019, p. 13",
        authoritative_reference: "CELEX:32019R0631",
        last_verified_on: "2026-04-21",
      },
    ],
    lifecycle_state: "ACTIVE",
    promoted_on: "2026-04-21",
    promoted_by: "phase-j-human-round-2-horizontal",
    trigger_logic: {
      mode: "declarative",
      match_mode: "all",
      conditions: [
        { field: "isPlugInHybrid", operator: "is_true", value: true, label: "Vehicle is a plug-in hybrid" },
        { field: "vehicleCategory", operator: "in", value: ["M1", "N1"], label: "Vehicle category is M1 or N1" },
      ],
      fallback_if_missing: "not_applicable",
    },
    temporal: {
      entry_into_force: null,
      applies_to_new_types_from: null,
      applies_to_all_new_vehicles_from: null,
      applies_to_first_registration_from: null,
      applies_from_generic: "2025-01-01",
      effective_to: null,
      small_volume_derogation_until: null,
      notes:
        "Revised UF methodology per Reg (EU) 2023/443 effective for new type-approvals from 2025-01-01; phased second step [verify 2027-01-01].",
    },
    obligation_text:
      "PHEV CO2 declared = CS-mode CO2 × (1 − UF) + CD-mode CO2 × UF, where UF is derived from WLTP electric range. Revised UF per Reg (EU) 2023/443 lowers real-world mismatch: declared CO2 increases, fleet CO2 credit decreases.",
    evidence_tasks: [
      "R101 test report (CO2 + fuel consumption per UF methodology)",
      "WLTP electric-range determination",
      "Utility-factor calculation worksheet",
      "Combined CO2 declaration (weighted CS + CD)",
      "CS-vs-CD CO2 breakdown per WLTC phase",
    ],
    owner_hint: "powertrain_emissions",
    ui_package: "wvta_core",
    process_stage: "type_approval",
    content_provenance: {
      source_type: "eur_lex",
      retrieved_at: "2026-04-21",
      human_reviewer: "yanhao",
    },
    related_rules: [
      { rule_id: "REG-UN-101", relation: "requires" },
      { rule_id: "REG-EM-003", relation: "complements" },
    ],
  }),
  makeSeedRule({
    stable_id: "REG-EM-010",
    title: "Diesel NOx After-Treatment (AdBlue/SCR)",
    short_label: "AdBlue / SCR",
    legal_family: "emissions_co2",
    jurisdiction: "EU",
    jurisdiction_level: "EU",
    framework_group: ["MN"],
    sources: [
      {
        label: "Euro 6d NOx limits (Annex I)",
        source_family: "EUR-Lex" as const,
        reference: "Regulation (EC) No 715/2007, Annex I (Euro 6d NOx 80 mg/km)",
        official_url: "https://eur-lex.europa.eu/eli/reg/2007/715/oj",
        oj_reference: "OJ L 171, 29.6.2007, p. 1",
        authoritative_reference: "CELEX:32007R0715",
        last_verified_on: "2026-04-21",
      },
      {
        label: "Euro 7 NOx tightening",
        source_family: "EUR-Lex" as const,
        reference: "Regulation (EU) 2024/1257 (Euro 7 — NOx 60 mg/km fuel-neutral + cold-start + extended RDE)",
        official_url: "https://eur-lex.europa.eu/eli/reg/2024/1257/oj",
        oj_reference: "OJ L, 2024/1257, 8 May 2024",
        authoritative_reference: "CELEX:32024R1257",
        last_verified_on: "2026-04-21",
      },
      {
        label: "RDE methodology (Annex IIIA)",
        source_family: "EUR-Lex" as const,
        reference: "Commission Regulation (EU) 2017/1151, Annex IIIA (RDE methodology)",
        official_url: "https://eur-lex.europa.eu/eli/reg/2017/1151/oj",
        oj_reference: "OJ L 175, 7.7.2017, p. 1",
        authoritative_reference: "CELEX:32017R1151",
        last_verified_on: "2026-04-21",
      },
    ],
    lifecycle_state: "ACTIVE",
    promoted_on: "2026-04-21",
    promoted_by: "phase-j-human-round-2-horizontal",
    trigger_logic: {
      mode: "declarative",
      match_mode: "all",
      conditions: [
        { field: "hasDieselEngine", operator: "is_true", value: true, label: "Vehicle has a diesel engine" },
      ],
      fallback_if_missing: "not_applicable",
    },
    temporal: {
      entry_into_force: null,
      applies_to_new_types_from: null,
      applies_to_all_new_vehicles_from: null,
      applies_to_first_registration_from: null,
      applies_from_generic: "2014-09-01",
      effective_to: null,
      small_volume_derogation_until: null,
      notes:
        "Euro 6d NOx 80 mg/km; Euro 7 tightens to 60 mg/km with extended RDE + cold-start from 2026-11-29 per Reg (EU) 2024/1257.",
    },
    obligation_text:
      "Diesel vehicles must meet NOx limit via SCR after-treatment with DEF/AdBlue dosing; tamper-proof fill, driver warnings on low tank, engine degradation (not shutdown) when DEF empty, in-service compliance monitoring. Euro 7 tightens NOx + adds cold-start + extended RDE.",
    evidence_tasks: [
      "SCR architecture specification + catalyst sizing",
      "DEF consumption-rate calculation per cycle",
      "Anti-tampering design documentation",
      "Driver HMI warning strategy (low-DEF cascade, degradation sequence)",
      "In-service compliance (ISC) test plan",
      "RDE NOx compliance report (PEMS)",
    ],
    owner_hint: "powertrain_emissions",
    ui_package: "wvta_core",
    process_stage: "type_approval",
    content_provenance: {
      source_type: "eur_lex",
      retrieved_at: "2026-04-21",
      human_reviewer: "yanhao",
    },
    prerequisite_standards: [
      "ISO 22241 (diesel engines — NOx reduction agent AUS 32)",
    ],
    related_rules: [
      { rule_id: "REG-UN-083", relation: "complements" },
    ],
  }),
  makeSeedRule({
    stable_id: "REG-EM-011",
    title: "CO2 + Fuel Consumption Consumer Labeling",
    short_label: "CO2 Labeling",
    legal_family: "emissions_co2",
    jurisdiction: "EU",
    jurisdiction_level: "EU",
    framework_group: ["MN"],
    sources: [
      {
        label: "Framework directive",
        source_family: "EUR-Lex" as const,
        reference: "Directive 1999/94/EC on the availability of consumer information on fuel economy and CO2 emissions in respect of new passenger cars",
        official_url: "https://eur-lex.europa.eu/eli/dir/1999/94/oj",
        oj_reference: "OJ L 12, 18.1.2000, p. 16",
        authoritative_reference: "CELEX:31999L0094",
        last_verified_on: "2026-04-21",
      },
    ],
    lifecycle_state: "ACTIVE",
    promoted_on: "2026-04-21",
    promoted_by: "phase-j-human-round-2-horizontal",
    trigger_logic: {
      mode: "declarative",
      match_mode: "all",
      conditions: [
        { field: "frameworkGroup", operator: "eq", value: "MN", label: "Framework group is MN" },
        { field: "vehicleCategory", operator: "eq", value: "M1", label: "Vehicle category is M1 (passenger car)" },
      ],
      fallback_if_missing: "not_applicable",
    },
    temporal: {
      entry_into_force: null,
      applies_to_new_types_from: null,
      applies_to_all_new_vehicles_from: null,
      applies_to_first_registration_from: null,
      applies_from_generic: "2001-01-18",
      effective_to: null,
      small_volume_derogation_until: null,
      notes:
        "WLTP-based values required from 2018-01-01. National label format varies per MS transposition (DE PKW-EnVKV [verify], FR arrêté 10 avril 2003 [verify], ES RD 837/2002 [verify]).",
    },
    obligation_text:
      "New M1 passenger cars must display at point of sale a label showing official fuel consumption (l/100km) + CO2 emissions (g/km). Brochures and web listings must include same data. PHEV: combined WLTP CO2 + electric-mode range. BEV: kWh/100km.",
    evidence_tasks: [
      "Point-of-sale label artwork approval per member-state format",
      "Dealer training package on label + brochure requirements",
      "Brochure template with fuel-economy / CO2 disclosure block",
      "Web-listing audit (compliance with MS-specific layout)",
    ],
    owner_hint: "homologation",
    ui_package: "market_access",
    process_stage: "sop",
    content_provenance: {
      source_type: "eur_lex",
      retrieved_at: "2026-04-21",
      human_reviewer: "yanhao",
    },
  }),
  makeSeedRule({
    stable_id: "REG-EM-012",
    title: "Heavy-Duty CO2 / VECTO",
    short_label: "HD CO2 / VECTO",
    legal_family: "emissions_co2",
    jurisdiction: "EU",
    jurisdiction_level: "EU",
    framework_group: ["MN"],
    sources: [
      {
        label: "VECTO simulation tool",
        source_family: "EUR-Lex" as const,
        reference: "Commission Regulation (EU) 2017/2400 establishing the VECTO simulation tool for heavy-duty CO2 and fuel consumption determination",
        official_url: "https://eur-lex.europa.eu/eli/reg/2017/2400/oj",
        oj_reference: "OJ L 349, 29.12.2017, p. 1",
        authoritative_reference: "CELEX:32017R2400",
        last_verified_on: "2026-04-21",
      },
      {
        label: "HD CO2 fleet targets",
        source_family: "EUR-Lex" as const,
        reference: "Regulation (EU) 2019/1242 setting CO2 performance standards for new heavy-duty vehicles",
        official_url: "https://eur-lex.europa.eu/eli/reg/2019/1242/oj",
        oj_reference: "OJ L 198, 25.7.2019, p. 202",
        authoritative_reference: "CELEX:32019R1242",
        last_verified_on: "2026-04-21",
      },
      {
        label: "HD CO2 monitoring",
        source_family: "EUR-Lex" as const,
        reference: "Regulation (EU) 2018/956 on the monitoring and reporting of CO2 emissions from and fuel consumption of new heavy-duty vehicles",
        official_url: "https://eur-lex.europa.eu/eli/reg/2018/956/oj",
        oj_reference: "OJ L 173, 9.7.2018, p. 1",
        authoritative_reference: "CELEX:32018R0956",
        last_verified_on: "2026-04-21",
      },
    ],
    lifecycle_state: "ACTIVE",
    promoted_on: "2026-04-21",
    promoted_by: "phase-j-human-round-2-horizontal",
    trigger_logic: {
      mode: "declarative",
      match_mode: "all",
      conditions: [
        { field: "vehicleCategory", operator: "in", value: ["M2", "M3", "N2", "N3"], label: "Vehicle category is heavy-duty (M2/M3/N2/N3)" },
        { field: "hasCombustionEngine", operator: "is_true", value: true, label: "Vehicle has a combustion engine" },
      ],
      fallback_if_missing: "not_applicable",
    },
    temporal: {
      entry_into_force: null,
      applies_to_new_types_from: "2025-01-01",
      applies_to_all_new_vehicles_from: null,
      applies_to_first_registration_from: null,
      applies_from_generic: "2019-01-01",
      effective_to: null,
      small_volume_derogation_until: null,
      notes:
        "Targets: -15% (2025), -45% (2030), -65% (2035), -90% (2040) [verify via Reg (EU) 2024/1610 amendment]. Applies primarily to Chinese HD OEMs (Foton, Sany, Yutong) — out of M1 pilot scope, registry completeness.",
    },
    obligation_text:
      "HD manufacturers must simulate vehicle CO2 using VECTO, declare per vehicle, submit annual monitoring data per Reg 2018/956, and meet fleet targets under Reg 2019/1242.",
    evidence_tasks: [
      "VECTO simulation reports per vehicle configuration",
      "Component certificates (engine, transmission, axle, tyres) feeding VECTO",
      "Fleet CO2 compliance planning model",
      "Annual CO2 monitoring submission per Reg (EU) 2018/956",
    ],
    owner_hint: "powertrain_emissions",
    planning_lead_time_months: 36,
    ui_package: "wvta_core",
    process_stage: "type_approval",
    content_provenance: {
      source_type: "eur_lex",
      retrieved_at: "2026-04-21",
      human_reviewer: "yanhao",
    },
  }),
  makeSeedRule({
    stable_id: "REG-EM-013",
    title: "Euro 7 — Combustion Exhaust + OBFCM",
    short_label: "Euro 7 (combustion)",
    legal_family: "emissions_co2",
    jurisdiction: "EU",
    jurisdiction_level: "EU",
    framework_group: ["MN"],
    sources: [
      {
        label: "Framework regulation",
        source_family: "EUR-Lex" as const,
        reference: "Regulation (EU) 2024/1257 (Euro 7 framework)",
        official_url: "https://eur-lex.europa.eu/eli/reg/2024/1257/oj",
        oj_reference: "OJ L, 2024/1257, 8 May 2024",
        authoritative_reference: "CELEX:32024R1257",
        last_verified_on: "2026-04-21",
      },
      {
        label: "Implementing regulation (exhaust/evaporative)",
        source_family: "Commission legal act" as const,
        reference: "Implementing Regulation (EU) 2025/1706",
        official_url: "https://eur-lex.europa.eu/eli/reg_impl/2025/1706/oj",
        oj_reference: "OJ L, 2025/1706, 5 September 2025",
        authoritative_reference: "CELEX:32025R1706",
        last_verified_on: "2026-04-21",
      },
      {
        label: "Implementing regulation (OBFCM/OBM/EVP)",
        source_family: "Commission legal act" as const,
        reference: "Implementing Regulation (EU) 2025/1707",
        official_url: "https://eur-lex.europa.eu/eli/reg_impl/2025/1707/oj",
        oj_reference: "OJ L, 2025/1707, 5 September 2025",
        authoritative_reference: "CELEX:32025R1707",
        last_verified_on: "2026-04-21",
      },
    ],
    lifecycle_state: "ACTIVE",
    promoted_on: "2026-04-21",
    promoted_by: "phase-j-human-round-2-horizontal",
    trigger_logic: {
      mode: "declarative",
      match_mode: "all",
      conditions: [
        { field: "frameworkGroup", operator: "eq", value: "MN", label: "Framework group is MN" },
        { field: "vehicleCategory", operator: "in", value: ["M1", "N1"], label: "Vehicle category is M1 or N1 (light-duty)" },
        { field: "hasCombustionEngine", operator: "is_true", value: true, label: "Vehicle has a combustion engine" },
      ],
      fallback_if_missing: "not_applicable",
    },
    temporal: {
      entry_into_force: "2024-05-28",
      applies_to_new_types_from: "2026-11-29",
      applies_to_all_new_vehicles_from: "2027-11-29",
      applies_to_first_registration_from: null,
      applies_from_generic: null,
      effective_to: null,
      small_volume_derogation_until: "2030-07-01",
      notes: null,
    },
    obligation_text:
      "M1/N1 combustion, hybrid, and plug-in-hybrid vehicles must meet Euro 7 exhaust limits (PN10, NOx 60 mg/km fuel-neutral, HC, CO), on-board monitoring (OBM), on-board fuel-consumption monitoring (OBFCM), extended RDE including cold-start + off-cycle.",
    evidence_tasks: [
      "Euro 7 exhaust test reports (PN10, NOx, HC, CO)",
      "OBM compliance per Impl Reg (EU) 2025/1707",
      "OBFCM device compliance + data structure",
      "Extended RDE cold-start + off-cycle report",
      "Environmental Vehicle Passport data payload",
    ],
    owner_hint: "powertrain_emissions",
    planning_lead_time_months: 24,
    ui_package: "wvta_core",
    process_stage: "type_approval",
    content_provenance: {
      source_type: "eur_lex",
      retrieved_at: "2026-04-21",
      human_reviewer: "yanhao",
    },
    related_rules: [
      { rule_id: "REG-EM-001", relation: "complements" },
      { rule_id: "REG-EM-014", relation: "complements" },
    ],
  }),
  makeSeedRule({
    stable_id: "REG-EM-014",
    title: "Euro 7 — Battery Durability",
    short_label: "Euro 7 (battery durability)",
    legal_family: "emissions_co2",
    jurisdiction: "EU",
    jurisdiction_level: "EU",
    framework_group: ["MN"],
    sources: [
      {
        label: "Framework regulation",
        source_family: "EUR-Lex" as const,
        reference: "Regulation (EU) 2024/1257 (Euro 7 framework — battery durability provisions)",
        official_url: "https://eur-lex.europa.eu/eli/reg/2024/1257/oj",
        oj_reference: "OJ L, 2024/1257, 8 May 2024",
        authoritative_reference: "CELEX:32024R1257",
        last_verified_on: null,
      },
    ],
    lifecycle_state: "SEED_UNVERIFIED",
    trigger_logic: {
      mode: "declarative",
      match_mode: "all",
      conditions: [
        { field: "frameworkGroup", operator: "eq", value: "MN", label: "Framework group is MN" },
        { field: "vehicleCategory", operator: "in", value: ["M1", "N1"], label: "Vehicle category is M1 or N1 (light-duty)" },
        { field: "batteryPresent", operator: "is_true", value: true, label: "Vehicle has a traction battery" },
      ],
      fallback_if_missing: "not_applicable",
    },
    temporal: {
      entry_into_force: "2024-05-28",
      applies_to_new_types_from: "2026-11-29",
      applies_to_all_new_vehicles_from: null,
      applies_to_first_registration_from: null,
      applies_from_generic: null,
      effective_to: null,
      small_volume_derogation_until: null,
      notes:
        "Detailed SOH thresholds + test methodology in Commission delegated act pending adoption [verify timing].",
    },
    obligation_text:
      "M1/N1 vehicles with traction batteries (BEV, HEV, PHEV) must demonstrate battery durability: SOH ≥ 80% at 5 years / 100 000 km; SOH ≥ 70% at 8 years / 160 000 km. On-board SOH monitoring per OBM specification in Impl Reg 2025/1707.",
    evidence_tasks: [
      "Battery durability test plan",
      "State-of-health (SOH) measurement methodology",
      "5-year / 100 000 km SOH report",
      "8-year / 160 000 km SOH report",
      "OBM SOH data recording specification",
    ],
    manual_review_reason:
      "Commission delegated act on battery durability under Reg (EU) 2024/1257 pending adoption [verify].",
    owner_hint: "powertrain_emissions",
    ui_package: "wvta_core",
    process_stage: "type_approval",
    content_provenance: {
      source_type: "eur_lex",
      retrieved_at: "2026-04-20",
      human_reviewer: null,
    },
    related_rules: [
      { rule_id: "REG-EM-001", relation: "complements" },
      { rule_id: "REG-BAT-001", relation: "complements" },
    ],
  }),
];
