import { makeSeedRule, makeSource } from "@/registry/seed/shared";

export const materialsChemicalsRules = [
  makeSeedRule({
    stable_id: "REG-BAT-001",
    title: "EU Battery Regulation",
    short_label: "Battery Regulation",
    legal_family: "materials_chemicals",
    jurisdiction: "EU",
    jurisdiction_level: "EU",
    framework_group: ["MN", "L"],
    sources: [
      {
        label: "Framework regulation",
        source_family: "EUR-Lex" as const,
        reference: "Regulation (EU) 2023/1542",
        official_url: "https://eur-lex.europa.eu/eli/reg/2023/1542/oj",
        oj_reference: "OJ L 191, 28.7.2023",
        authoritative_reference: "CELEX:32023R1542",
        last_verified_on: "2026-04-16",
      },
    ],
    lifecycle_state: "ACTIVE",
    promoted_on: "2026-04-16",
    promoted_by: "phase-11b2",
    trigger_logic: {
      mode: "declarative",
      match_mode: "all",
      conditions: [{ field: "batteryPresent", operator: "is_true", value: true }],
      fallback_if_missing: "not_applicable",
    },
    temporal: {
      entry_into_force: "2023-08-17",
      applies_to_new_types_from: null,
      applies_to_all_new_vehicles_from: null,
      applies_to_first_registration_from: null,
      applies_from_generic: "2024-02-18",
      effective_to: null,
      small_volume_derogation_until: null,
      notes:
        "Multiple sub-obligations have different dates (2024-2031). Parent rule only in Phase 2.",
    },
    obligation_text:
      "Traction batteries must comply with sustainability, labeling, battery passport, due diligence, and end-of-life obligations per phased schedule.",
    owner_hint: "sustainability_materials",
    ui_package: "horizontal",
    process_stage: "post_market",
  }),
  makeSeedRule({
    stable_id: "REG-BAT-002",
    title: "REACH",
    short_label: "REACH",
    legal_family: "materials_chemicals",
    jurisdiction: "EU",
    jurisdiction_level: "EU",
    framework_group: ["MN", "L", "O", "AGRI"],
    sources: [makeSource("Framework regulation", "EUR-Lex", "Regulation (EC) No 1907/2006")],
    lifecycle_state: "SEED_UNVERIFIED",
    trigger_logic: {
      mode: "declarative",
      match_mode: "all",
      conditions: [],
      fallback_if_missing: "unknown",
    },
    obligation_text:
      "Communicate SVHC presence in articles and comply with REACH restrictions.",
    owner_hint: "sustainability_materials",
    ui_package: "horizontal",
    process_stage: "post_market",
  }),
  makeSeedRule({
    stable_id: "REG-BAT-003",
    title: "End-of-Life Vehicles Revision",
    short_label: "ELV",
    legal_family: "materials_chemicals",
    jurisdiction: "EU",
    jurisdiction_level: "EU",
    framework_group: ["MN", "L", "O", "AGRI"],
    sources: [makeSource("Revision item", "Commission guidance", "ELV Directive revision into Regulation")],
    lifecycle_state: "DRAFT",
    trigger_logic: {
      mode: "declarative",
      match_mode: "all",
      conditions: [],
      fallback_if_missing: "unknown",
    },
    obligation_text:
      "ELV Directive revision into a regulation is pending and remains a draft monitoring item.",
    owner_hint: "sustainability_materials",
    notes: "ELV Directive revision into Regulation pending.",
    ui_package: "horizontal",
    process_stage: "post_market",
  }),
  makeSeedRule({
    stable_id: "REG-BAT-004",
    title: "Battery Due Diligence — Supply Chain",
    short_label: "Battery Due Diligence",
    legal_family: "materials_chemicals",
    jurisdiction: "EU",
    jurisdiction_level: "EU",
    framework_group: ["MN", "L"],
    sources: [
      {
        label: "Framework regulation",
        source_family: "EUR-Lex" as const,
        reference: "Regulation (EU) 2023/1542, Articles 47-52 (supply chain due diligence)",
        official_url: "https://eur-lex.europa.eu/eli/reg/2023/1542/oj",
        oj_reference: "OJ L 191, 28.7.2023, p. 1",
        authoritative_reference: "CELEX:32023R1542",
        last_verified_on: "2026-04-17",
      },
    ],
    lifecycle_state: "ACTIVE",
    promoted_on: "2026-04-17",
    promoted_by: "phase-11b2-batch2",
    trigger_logic: {
      mode: "declarative",
      match_mode: "all",
      conditions: [{ field: "batteryPresent", operator: "is_true", value: true }],
      fallback_if_missing: "not_applicable",
    },
    temporal: {
      entry_into_force: "2023-08-17",
      applies_to_new_types_from: null,
      applies_to_all_new_vehicles_from: null,
      applies_to_first_registration_from: null,
      applies_from_generic: "2025-08-18",
      effective_to: null,
      small_volume_derogation_until: null,
      notes:
        "Chapter VII supply-chain due diligence obligations apply from 18 August 2025 per Art. 96(2)(a). SMEs are exempt (Art. 47(1)).",
    },
    obligation_text:
      "Economic operators placing batteries on the EU market must establish and implement a supply chain due diligence policy covering cobalt, natural graphite, lithium, and nickel, including risk identification, mitigation, and third-party verification.",
    evidence_tasks: [
      "Supply-chain due diligence policy and management system",
      "Risk-identification documentation for cobalt/graphite/lithium/nickel",
      "Third-party verification report",
      "Annual due-diligence report (public disclosure)",
    ],
    owner_hint: "sustainability_materials",
    planning_lead_time_months: 12,
    ui_package: "horizontal",
    process_stage: "pre_ta",
  }),
  makeSeedRule({
    stable_id: "REG-BAT-005",
    title: "Digital Battery Passport",
    short_label: "Battery Passport",
    legal_family: "materials_chemicals",
    jurisdiction: "EU",
    jurisdiction_level: "EU",
    framework_group: ["MN", "L"],
    sources: [
      {
        label: "Framework regulation",
        source_family: "EUR-Lex" as const,
        reference: "Regulation (EU) 2023/1542, Articles 65-70 (battery passport)",
        official_url: "https://eur-lex.europa.eu/eli/reg/2023/1542/oj",
        oj_reference: "OJ L 191, 28.7.2023, p. 1",
        authoritative_reference: "CELEX:32023R1542",
        last_verified_on: "2026-04-17",
      },
    ],
    lifecycle_state: "ACTIVE",
    promoted_on: "2026-04-17",
    promoted_by: "phase-11b2-batch2",
    trigger_logic: {
      mode: "declarative",
      match_mode: "all",
      conditions: [{ field: "batteryPresent", operator: "is_true", value: true }],
      fallback_if_missing: "not_applicable",
    },
    temporal: {
      entry_into_force: "2023-08-17",
      applies_to_new_types_from: null,
      applies_to_all_new_vehicles_from: null,
      applies_to_first_registration_from: null,
      applies_from_generic: "2027-02-18",
      effective_to: null,
      small_volume_derogation_until: null,
      notes:
        "Battery passport applies from 18 February 2027 for LMT, EV, and industrial (>2 kWh) batteries per Art. 77 / Annex XIII.",
    },
    obligation_text:
      "Each traction battery must have a digital battery passport containing identification, composition, carbon footprint, performance, durability, and recycling information accessible via QR code linked to each battery's unique identifier.",
    evidence_tasks: [
      "Battery passport data model aligned to Annex XIII",
      "Unique battery identifier issuance process",
      "QR code carrier on battery / battery-pack label",
      "Backend infrastructure to host and update passport content",
    ],
    owner_hint: "sustainability_materials",
    planning_lead_time_months: 18,
    ui_package: "horizontal",
    process_stage: "sop",
  }),
  makeSeedRule({
    stable_id: "REG-BAT-006",
    title: "Battery Carbon Footprint Declaration",
    short_label: "Battery CO2 Footprint",
    legal_family: "materials_chemicals",
    jurisdiction: "EU",
    jurisdiction_level: "EU",
    framework_group: ["MN", "L"],
    sources: [
      makeSource(
        "Framework regulation",
        "EUR-Lex",
        "Regulation (EU) 2023/1542, Article 7 (carbon footprint declaration)",
        "OJ L 191, 28.7.2023",
      ),
    ],
    lifecycle_state: "SEED_UNVERIFIED",
    trigger_logic: {
      mode: "declarative",
      match_mode: "all",
      conditions: [{ field: "batteryPresent", operator: "is_true", value: true }],
      fallback_if_missing: "not_applicable",
    },
    obligation_text:
      "EV batteries placed on the EU market must carry a carbon footprint declaration per life-cycle stage. Performance class labels will follow.",
    owner_hint: "sustainability_materials",
    ui_package: "horizontal",
    process_stage: "pre_ta",
  }),
  makeSeedRule({
    stable_id: "REG-BAT-007",
    title: "SCIP Database Notification for SVHC in Vehicles",
    short_label: "SCIP / SVHC",
    legal_family: "materials_chemicals",
    jurisdiction: "EU",
    jurisdiction_level: "EU",
    framework_group: ["MN", "L", "O", "AGRI"],
    sources: [
      makeSource(
        "EU agency requirement",
        "ECHA",
        "SCIP database under Waste Framework Directive 2008/98/EC, Art. 9(1)(i)",
      ),
    ],
    lifecycle_state: "SEED_UNVERIFIED",
    trigger_logic: {
      mode: "declarative",
      match_mode: "all",
      conditions: [{ field: "targetsEU", operator: "is_true", value: true }],
      fallback_if_missing: "unknown",
    },
    obligation_text:
      "Suppliers of articles containing SVHCs above 0.1% w/w must submit notifications to the ECHA SCIP database before placing on the EU market.",
    owner_hint: "sustainability_materials",
    ui_package: "horizontal",
    process_stage: "pre_ta",
  }),
];
