import { makeSeedRule, makeSource } from "@/registry/seed/shared";

export const materialsChemicalsRules = [
  makeSeedRule({
    stable_id: "REG-BAT-001",
    title: "EU Battery Regulation",
    short_label: "Battery Regulation",
    legal_family: "materials_chemicals",
    jurisdiction: "EU",
    jurisdiction_level: "EU",
    framework_group: ["MN", "L"],
    sources: [
      {
        label: "Framework regulation",
        source_family: "EUR-Lex" as const,
        reference: "Regulation (EU) 2023/1542",
        official_url: "https://eur-lex.europa.eu/eli/reg/2023/1542/oj",
        oj_reference: "OJ L 191, 28.7.2023",
        authoritative_reference: "CELEX:32023R1542",
        last_verified_on: "2026-04-16",
      },
    ],
    lifecycle_state: "ACTIVE",
    promoted_on: "2026-04-16",
    promoted_by: "phase-11b2",
    trigger_logic: {
      mode: "declarative",
      match_mode: "all",
      conditions: [{ field: "batteryPresent", operator: "is_true", value: true }],
      fallback_if_missing: "not_applicable",
    },
    temporal: {
      entry_into_force: "2023-08-17",
      applies_to_new_types_from: null,
      applies_to_all_new_vehicles_from: null,
      applies_to_first_registration_from: null,
      applies_from_generic: "2024-02-18",
      effective_to: null,
      small_volume_derogation_until: null,
      notes:
        "Multiple sub-obligations have different dates (2024-2031). Parent rule only in Phase 2.",
    },
    obligation_text:
      "Traction batteries must comply with sustainability, labeling, battery passport, due diligence, and end-of-life obligations per phased schedule.",
    owner_hint: "sustainability_materials",
    ui_package: "horizontal",
    process_stage: "post_market",
    prerequisite_standards: [
      "IEC 62619 (secondary cells and batteries — industrial applications safety)",
      "ISO 12405 (electrically propelled road vehicles — traction battery packs and systems)",
    ],
    related_rules: [{ rule_id: "REG-UN-100", relation: "complements" }],
  }),
  makeSeedRule({
    stable_id: "REG-BAT-002",
    title: "REACH",
    short_label: "REACH",
    legal_family: "materials_chemicals",
    jurisdiction: "EU",
    jurisdiction_level: "EU",
    framework_group: ["MN", "L", "O", "AGRI"],
    sources: [makeSource("Framework regulation", "EUR-Lex", "Regulation (EC) No 1907/2006")],
    lifecycle_state: "SEED_UNVERIFIED",
    trigger_logic: {
      mode: "declarative",
      match_mode: "all",
      conditions: [],
      fallback_if_missing: "unknown",
    },
    obligation_text:
      "Communicate SVHC presence in articles and comply with REACH restrictions.",
    owner_hint: "sustainability_materials",
    ui_package: "horizontal",
    process_stage: "post_market",
  }),
  makeSeedRule({
    stable_id: "REG-BAT-003",
    title: "End-of-Life Vehicles Revision",
    short_label: "ELV",
    legal_family: "materials_chemicals",
    jurisdiction: "EU",
    jurisdiction_level: "EU",
    framework_group: ["MN", "L", "O", "AGRI"],
    sources: [
      {
        label: "Framework directive",
        source_family: "EUR-Lex" as const,
        reference: "Directive 2000/53/EC on end-of-life vehicles",
        official_url: "https://eur-lex.europa.eu/eli/dir/2000/53/oj",
        oj_reference: "OJ L 269, 21.10.2000, p. 34",
        authoritative_reference: "CELEX:32000L0053",
        last_verified_on: null,
      },
      {
        label: "Commission revision proposal",
        source_family: "European Commission" as const,
        reference: "COM(2023) 451 (ELV revision into Regulation — provisional agreement 12 December 2025, pending final adoption)",
        official_url: "https://www.europarl.europa.eu/legislative-train/theme-a-european-green-deal/file-revision-of-eu-rules-on-end-of-life-vehicles-and-type-approval-of-motor-vehicles",
        oj_reference: null,
        authoritative_reference: null,
        last_verified_on: null,
      },
    ],
    lifecycle_state: "SEED_UNVERIFIED",
    trigger_logic: {
      mode: "declarative",
      match_mode: "any",
      conditions: [
        { field: "batteryPresent", operator: "is_true", value: true },
        { field: "vehicleCategory", operator: "in", value: ["M1", "N1"] },
      ],
      fallback_if_missing: "not_applicable",
    },
    temporal: {
      entry_into_force: "2000-10-21",
      applies_to_new_types_from: null,
      applies_to_all_new_vehicles_from: null,
      applies_to_first_registration_from: null,
      applies_from_generic: "2002-04-21",
      effective_to: null,
      small_volume_derogation_until: null,
      notes:
        "Dir 2000/53/EC in force. Revision into Regulation (COM(2023) 451) provisionally agreed 2025-12-12, Coreper endorsed 2026-02-25; not yet adopted or repealing date set [verify]. Original 2006-01-01 interim targets (85/80%) superseded by 2015-01-01 targets (95/85%).",
    },
    obligation_text:
      "Motor vehicle producers must operate/fund end-of-life vehicle take-back at no cost to last holder; authorised treatment facilities must meet 95% reuse+recovery + 85% reuse+recycling by weight per vehicle per year (from 2015-01-01). Producers must provide dismantling information within 6 months of new-type launch per Art. 8. Pending Regulation revision strengthens circularity (recycled-plastic content phase-in 15%@+6y / 25%@+10y).",
    evidence_tasks: [
      "ELV take-back network agreement per member state",
      "Producer-responsibility scheme registration (SIG in ES, ADEME in FR, AltfahrzeugV contract in DE)",
      "Art. 8 dismantling information sheet published within 6 months of new-type launch",
      "Recyclate-content declaration (per pending Regulation)",
      "Annual 95% recovery / 85% recycling target compliance reporting",
    ],
    manual_review_reason:
      "Directive 2000/53/EC verified in current form. Revision to Regulation (COM(2023) 451) awaiting final adoption — monitor OJ.",
    owner_hint: "sustainability_materials",
    ui_package: "horizontal",
    process_stage: "post_market",
    content_provenance: {
      source_type: "eur_lex",
      retrieved_at: "2026-04-20",
      human_reviewer: null,
    },
  }),
  makeSeedRule({
    stable_id: "REG-BAT-004",
    title: "Battery Due Diligence — Supply Chain",
    short_label: "Battery Due Diligence",
    legal_family: "materials_chemicals",
    jurisdiction: "EU",
    jurisdiction_level: "EU",
    framework_group: ["MN", "L"],
    sources: [
      {
        label: "Framework regulation",
        source_family: "EUR-Lex" as const,
        reference: "Regulation (EU) 2023/1542, Articles 47-52 (supply chain due diligence)",
        official_url: "https://eur-lex.europa.eu/eli/reg/2023/1542/oj",
        oj_reference: "OJ L 191, 28.7.2023, p. 1",
        authoritative_reference: "CELEX:32023R1542",
        last_verified_on: "2026-04-17",
      },
    ],
    lifecycle_state: "ACTIVE",
    promoted_on: "2026-04-17",
    promoted_by: "phase-11b2-batch2",
    trigger_logic: {
      mode: "declarative",
      match_mode: "all",
      conditions: [{ field: "batteryPresent", operator: "is_true", value: true }],
      fallback_if_missing: "not_applicable",
    },
    temporal: {
      entry_into_force: "2023-08-17",
      applies_to_new_types_from: null,
      applies_to_all_new_vehicles_from: null,
      applies_to_first_registration_from: null,
      applies_from_generic: "2025-08-18",
      effective_to: null,
      small_volume_derogation_until: null,
      notes:
        "Chapter VII supply-chain due diligence obligations apply from 18 August 2025 per Art. 96(2)(a). SMEs are exempt (Art. 47(1)).",
    },
    obligation_text:
      "Economic operators placing batteries on the EU market must establish and implement a supply chain due diligence policy covering cobalt, natural graphite, lithium, and nickel, including risk identification, mitigation, and third-party verification.",
    evidence_tasks: [
      "Supply-chain due diligence policy and management system",
      "Risk-identification documentation for cobalt/graphite/lithium/nickel",
      "Third-party verification report",
      "Annual due-diligence report (public disclosure)",
    ],
    owner_hint: "sustainability_materials",
    planning_lead_time_months: 12,
    ui_package: "horizontal",
    process_stage: "pre_ta",
  }),
  makeSeedRule({
    stable_id: "REG-BAT-005",
    title: "Digital Battery Passport",
    short_label: "Battery Passport",
    legal_family: "materials_chemicals",
    jurisdiction: "EU",
    jurisdiction_level: "EU",
    framework_group: ["MN", "L"],
    sources: [
      {
        label: "Framework regulation",
        source_family: "EUR-Lex" as const,
        reference: "Regulation (EU) 2023/1542, Articles 65-70 (battery passport)",
        official_url: "https://eur-lex.europa.eu/eli/reg/2023/1542/oj",
        oj_reference: "OJ L 191, 28.7.2023, p. 1",
        authoritative_reference: "CELEX:32023R1542",
        last_verified_on: "2026-04-17",
      },
    ],
    lifecycle_state: "ACTIVE",
    promoted_on: "2026-04-17",
    promoted_by: "phase-11b2-batch2",
    trigger_logic: {
      mode: "declarative",
      match_mode: "all",
      conditions: [{ field: "batteryPresent", operator: "is_true", value: true }],
      fallback_if_missing: "not_applicable",
    },
    temporal: {
      entry_into_force: "2023-08-17",
      applies_to_new_types_from: null,
      applies_to_all_new_vehicles_from: null,
      applies_to_first_registration_from: null,
      applies_from_generic: "2027-02-18",
      effective_to: null,
      small_volume_derogation_until: null,
      notes:
        "Battery passport applies from 18 February 2027 for LMT, EV, and industrial (>2 kWh) batteries per Art. 77 / Annex XIII.",
    },
    obligation_text:
      "Each traction battery must have a digital battery passport containing identification, composition, carbon footprint, performance, durability, and recycling information accessible via QR code linked to each battery's unique identifier.",
    evidence_tasks: [
      "Battery passport data model aligned to Annex XIII",
      "Unique battery identifier issuance process",
      "QR code carrier on battery / battery-pack label",
      "Backend infrastructure to host and update passport content",
    ],
    owner_hint: "sustainability_materials",
    planning_lead_time_months: 18,
    ui_package: "horizontal",
    process_stage: "sop",
  }),
  makeSeedRule({
    stable_id: "REG-BAT-006",
    title: "Battery Carbon Footprint Declaration",
    short_label: "Battery CO2 Footprint",
    legal_family: "materials_chemicals",
    jurisdiction: "EU",
    jurisdiction_level: "EU",
    framework_group: ["MN", "L"],
    sources: [
      makeSource(
        "Framework regulation",
        "EUR-Lex",
        "Regulation (EU) 2023/1542, Article 7 (carbon footprint declaration)",
        "OJ L 191, 28.7.2023",
      ),
    ],
    lifecycle_state: "SEED_UNVERIFIED",
    trigger_logic: {
      mode: "declarative",
      match_mode: "all",
      conditions: [{ field: "batteryPresent", operator: "is_true", value: true }],
      fallback_if_missing: "not_applicable",
    },
    obligation_text:
      "EV batteries placed on the EU market must carry a carbon footprint declaration per life-cycle stage. Performance class labels will follow.",
    owner_hint: "sustainability_materials",
    ui_package: "horizontal",
    process_stage: "pre_ta",
  }),
  makeSeedRule({
    stable_id: "REG-BAT-007",
    title: "SCIP Database Notification for SVHC in Vehicles",
    short_label: "SCIP / SVHC",
    legal_family: "materials_chemicals",
    jurisdiction: "EU",
    jurisdiction_level: "EU",
    framework_group: ["MN", "L", "O", "AGRI"],
    sources: [
      makeSource(
        "EU agency requirement",
        "ECHA",
        "SCIP database under Waste Framework Directive 2008/98/EC, Art. 9(1)(i)",
      ),
    ],
    lifecycle_state: "SEED_UNVERIFIED",
    trigger_logic: {
      mode: "declarative",
      match_mode: "all",
      conditions: [{ field: "targetsEU", operator: "is_true", value: true }],
      fallback_if_missing: "unknown",
    },
    obligation_text:
      "Suppliers of articles containing SVHCs above 0.1% w/w must submit notifications to the ECHA SCIP database before placing on the EU market.",
    owner_hint: "sustainability_materials",
    ui_package: "horizontal",
    process_stage: "pre_ta",
  }),
  makeSeedRule({
    stable_id: "REG-BAT-008",
    title: "Battery Performance & Durability Declaration",
    short_label: "Battery Performance Class",
    legal_family: "materials_chemicals",
    jurisdiction: "EU",
    jurisdiction_level: "EU",
    framework_group: ["MN", "L"],
    sources: [
      {
        label: "Framework regulation",
        source_family: "EUR-Lex" as const,
        reference: "Regulation (EU) 2023/1542, Article 10 + Annex IV (performance and durability)",
        official_url: "https://eur-lex.europa.eu/eli/reg/2023/1542/oj",
        oj_reference: "OJ L 191, 28.7.2023",
        authoritative_reference: "CELEX:32023R1542",
        last_verified_on: "2026-04-21",
      },
    ],
    lifecycle_state: "ACTIVE",
    promoted_on: "2026-04-21",
    promoted_by: "phase-j-human-round-2-horizontal",
    trigger_logic: {
      mode: "declarative",
      match_mode: "all",
      conditions: [
        { field: "batteryPresent", operator: "is_true", value: true },
        {
          field: "vehicleCategory",
          operator: "in",
          value: ["M1", "N1", "L1e", "L2e", "L3e", "L4e", "L5e", "L6e", "L7e"],
        },
      ],
      fallback_if_missing: "not_applicable",
    },
    temporal: {
      entry_into_force: "2023-08-17",
      applies_to_new_types_from: null,
      applies_to_all_new_vehicles_from: null,
      applies_to_first_registration_from: null,
      applies_from_generic: "2027-08-18",
      effective_to: null,
      small_volume_derogation_until: null,
      notes:
        "Art. 10 performance class labeling for LMT and EV batteries applies from 18 August 2027 [verify final Commission Implementing Regulation on label format].",
    },
    obligation_text:
      "EV and Light-Means-of-Transport (LMT) batteries placed on the EU market must carry a performance-class label declaring rated capacity, power capability, internal resistance, energy efficiency round-trip, and expected lifespan per Annex IV methodology. Performance classes are set by Commission Implementing Regulation.",
    evidence_tasks: [
      "Performance test report per Annex IV methodology",
      "Internal resistance + power capability data sheet",
      "Rated-capacity declaration + expected-lifespan estimate",
      "Label artwork approval per Commission Implementing Reg format",
      "Supplier chain-of-custody for battery cell performance data",
    ],
    related_rules: [
      { rule_id: "REG-BAT-001", relation: "complements" },
      { rule_id: "REG-BAT-005", relation: "complements" },
    ],
    manual_review_reason:
      "Art. 10 Commission Implementing Regulation on label format pending [verify].",
    owner_hint: "sustainability_materials",
    ui_package: "horizontal",
    process_stage: "sop",
    content_provenance: {
      source_type: "eur_lex",
      retrieved_at: "2026-04-21",
      human_reviewer: "yanhao",
    },
  }),
  makeSeedRule({
    stable_id: "REG-BAT-009",
    title: "Battery Labeling & Marking",
    short_label: "Battery Labeling",
    legal_family: "materials_chemicals",
    jurisdiction: "EU",
    jurisdiction_level: "EU",
    framework_group: ["MN", "L"],
    sources: [
      {
        label: "Framework regulation",
        source_family: "EUR-Lex" as const,
        reference: "Regulation (EU) 2023/1542, Article 13 + Annex VI (labeling and marking)",
        official_url: "https://eur-lex.europa.eu/eli/reg/2023/1542/oj",
        oj_reference: "OJ L 191, 28.7.2023",
        authoritative_reference: "CELEX:32023R1542",
        last_verified_on: "2026-04-21",
      },
    ],
    lifecycle_state: "ACTIVE",
    promoted_on: "2026-04-21",
    promoted_by: "phase-j-human-round-2-horizontal",
    trigger_logic: {
      mode: "declarative",
      match_mode: "all",
      conditions: [{ field: "batteryPresent", operator: "is_true", value: true }],
      fallback_if_missing: "not_applicable",
    },
    temporal: {
      entry_into_force: "2023-08-17",
      applies_to_new_types_from: null,
      applies_to_all_new_vehicles_from: null,
      applies_to_first_registration_from: null,
      applies_from_generic: "2026-08-18",
      effective_to: null,
      small_volume_derogation_until: null,
      notes:
        "Art. 13 labeling applies from 18 August 2026. Crossed-out-wheeled-bin symbol applies from 18 August 2025 [verify dates against latest Commission delegated acts].",
    },
    obligation_text:
      "All batteries placed on the EU market must carry the crossed-out wheeled bin symbol indicating separate collection, plus battery-specific markings: rated capacity, chemistry identifier (Li-ion, NiMH, etc.), CE conformity mark, hazardous-substance indicators per Annex VI, and QR code linking to digital battery passport (for LMT, EV and industrial batteries >2 kWh).",
    evidence_tasks: [
      "Battery label artwork + QR code encoding specification",
      "Chemistry identifier per Annex VI",
      "Hazardous-substance declarations (Cd, Pb, Hg thresholds)",
      "CE marking dossier for the battery assembly",
      "Passport-link QR encoding aligned with REG-BAT-005 identifier",
    ],
    related_rules: [
      { rule_id: "REG-BAT-001", relation: "complements" },
      { rule_id: "REG-BAT-005", relation: "complements" },
    ],
    owner_hint: "sustainability_materials",
    ui_package: "horizontal",
    process_stage: "sop",
    content_provenance: {
      source_type: "eur_lex",
      retrieved_at: "2026-04-21",
      human_reviewer: "yanhao",
    },
  }),
  makeSeedRule({
    stable_id: "REG-BAT-010",
    title: "Recycled Content Declaration",
    short_label: "Recycled Content",
    legal_family: "materials_chemicals",
    jurisdiction: "EU",
    jurisdiction_level: "EU",
    framework_group: ["MN", "L"],
    sources: [
      {
        label: "Framework regulation",
        source_family: "EUR-Lex" as const,
        reference: "Regulation (EU) 2023/1542, Article 8 (recycled content declaration)",
        official_url: "https://eur-lex.europa.eu/eli/reg/2023/1542/oj",
        oj_reference: "OJ L 191, 28.7.2023",
        authoritative_reference: "CELEX:32023R1542",
        last_verified_on: null,
      },
    ],
    lifecycle_state: "DRAFT",
    trigger_logic: {
      mode: "declarative",
      match_mode: "all",
      conditions: [
        { field: "batteryPresent", operator: "is_true", value: true },
        {
          field: "vehicleCategory",
          operator: "in",
          value: ["M1", "N1", "L3e", "L4e", "L5e", "L6e", "L7e"],
        },
      ],
      fallback_if_missing: "not_applicable",
    },
    temporal: {
      entry_into_force: "2023-08-17",
      applies_to_new_types_from: null,
      applies_to_all_new_vehicles_from: null,
      applies_to_first_registration_from: null,
      applies_from_generic: "2028-08-18",
      effective_to: null,
      small_volume_derogation_until: null,
      notes:
        "Art. 8 declaration of recycled cobalt/lithium/lead/nickel content applies from 18 August 2028. Minimum recycled-content quotas (Art. 8(2)) phase in 2031 (Co 16% / Pb 85% / Li 6% / Ni 6%) and 2036 (Co 26% / Pb 85% / Li 12% / Ni 15%) [verify exact thresholds against consolidated text + latest methodology regulation].",
    },
    obligation_text:
      "Industrial batteries >2 kWh, EV batteries, and starter/LMT batteries containing cobalt, lithium, lead, or nickel must declare the share of recycled content of each metal in active materials, per Commission methodology. Declaration applies from 18 August 2028; minimum quotas phase in from 2031.",
    evidence_tasks: [
      "Recycled-content calculation per Commission methodology (pending)",
      "Supply chain documentation of recycled-metal share per cell component",
      "Third-party verification of recycled-content declaration",
      "Annual declaration update per methodology regulation",
    ],
    related_rules: [
      { rule_id: "REG-BAT-001", relation: "complements" },
      { rule_id: "REG-BAT-004", relation: "complements" },
    ],
    manual_review_reason:
      "Commission methodology regulation for recycled-content declaration pending [verify adoption timing]. Minimum quota percentages [verify].",
    owner_hint: "sustainability_materials",
    ui_package: "horizontal",
    process_stage: "pre_ta",
    content_provenance: {
      source_type: "eur_lex",
      retrieved_at: "2026-04-20",
      human_reviewer: null,
    },
  }),
  makeSeedRule({
    stable_id: "REG-CSRD-001",
    title: "Corporate Sustainability Reporting Directive",
    short_label: "CSRD",
    legal_family: "materials_chemicals",
    jurisdiction: "EU",
    jurisdiction_level: "EU",
    framework_group: ["MN", "L", "O", "AGRI"],
    sources: [
      makeSource(
        "Framework directive",
        "EUR-Lex",
        "Directive (EU) 2022/2464 (CSRD)",
      ),
    ],
    lifecycle_state: "PLACEHOLDER",
    trigger_logic: {
      mode: "declarative",
      match_mode: "all",
      conditions: [],
      fallback_if_missing: "unknown",
    },
    obligation_text:
      "Pending Phase 14 authoring — vehicle-specific delegated act not yet published",
    owner_hint: "sustainability_materials",
    notes:
      "CSRD sets sustainability reporting and ESRS obligations. A vehicle-sector-specific delegated act was anticipated but has been de-scoped by subsequent Omnibus legislation; the vehicle-sector reporting scope requires renewed review before authoring.",
    ui_package: "horizontal",
    process_stage: "post_market",
  }),
  makeSeedRule({
    stable_id: "REG-ESPR-001",
    title: "Ecodesign for Sustainable Products Regulation",
    short_label: "ESPR",
    legal_family: "materials_chemicals",
    jurisdiction: "EU",
    jurisdiction_level: "EU",
    framework_group: ["MN", "L", "O", "AGRI"],
    sources: [
      makeSource(
        "Framework regulation",
        "EUR-Lex",
        "Regulation (EU) 2024/1781 (ESPR)",
      ),
    ],
    lifecycle_state: "PLACEHOLDER",
    trigger_logic: {
      mode: "declarative",
      match_mode: "all",
      conditions: [],
      fallback_if_missing: "unknown",
    },
    obligation_text:
      "Pending Phase 14 authoring — vehicle-specific delegated act not yet published",
    owner_hint: "sustainability_materials",
    notes:
      "ESPR Art. 2(1)(h) excludes motor vehicles from horizontal product requirements. Monitor Commission work for any tangential scopes (e.g. tyres, spare parts, digital product passport for vehicle components) that may be brought under ESPR via future delegated acts.",
    ui_package: "horizontal",
    process_stage: "post_market",
  }),
];
