import { makeSeedRule } from "@/registry/seed/shared";

export const nonEuMarketRules = [
  makeSeedRule({
    stable_id: "REG-UK-001",
    title: "UK Automated Vehicles Act 2024",
    short_label: "UK AV Act",
    legal_family: "non_eu_market",
    jurisdiction: "UK",
    jurisdiction_level: "NON_EU_MARKET",
    framework_group: ["MN"],
    sources: [
      {
        label: "UK primary legislation",
        source_family: "UK Parliament" as const,
        reference: "Automated Vehicles Act 2024 (c. 10)",
        official_url: "https://www.legislation.gov.uk/ukpga/2024/10/contents",
        oj_reference: null,
        authoritative_reference: "UKPGA/2024/10",
        last_verified_on: "2026-04-17",
      },
    ],
    lifecycle_state: "ACTIVE",
    promoted_on: "2026-04-17",
    promoted_by: "phase-11b2-batch2",
    trigger_logic: {
      mode: "declarative",
      match_mode: "all",
      conditions: [
        { field: "targetCountries", operator: "includes", value: "UK" },
        { field: "isL3Plus", operator: "is_true", value: true },
      ],
      fallback_if_missing: "not_applicable",
    },
    temporal: {
      entry_into_force: "2024-05-20",
      applies_to_new_types_from: null,
      applies_to_all_new_vehicles_from: null,
      applies_to_first_registration_from: null,
      applies_from_generic: "2024-05-20",
      effective_to: null,
      small_volume_derogation_until: null,
      notes:
        "Primary legislation enacted 20 May 2024. Secondary legislation (authorisation procedures, NUIC/user-in-charge duties, reporting) still being consulted on by DfT — monitor 2025-2026 SIs for operational gates.",
    },
    obligation_text:
      "Authorisation of self-driving vehicles in Great Britain requires an Authorisation Certificate under Part 1; ASDEs and licensed no-user-in-charge (NUIC) operators carry ongoing duties including reporting and statement of safety principles compliance.",
    evidence_tasks: [
      "Self-driving feature safety case",
      "Authorisation Certificate application pack",
      "Statement of Safety Principles compliance evidence",
      "In-use reporting and incident-response procedure",
      "NUIC operator licence documentation (where applicable)",
    ],
    owner_hint: "regulatory_affairs",
    planning_lead_time_months: 24,
    ui_package: "market_access",
    process_stage: "pre_ta",
  }),

  // ============================================================
  // Phase I.3 — UK Non-EU-Market Overlay
  // 12 SEED_UNVERIFIED / DRAFT rules covering GB type-approval,
  // DVLA registration, MoT, VED, motor insurance, London ULEZ,
  // regional CAZ, Scotland LEZ, ZEV mandate, Windsor Framework NI,
  // UK GDPR, and Public Charge Point Regs.
  // Sources: legislation.gov.uk (Acts + SIs), gov.uk, TfL, milieuzones.
  // [verify] markers flag SI numbers, dates, and figures awaiting
  // human verification.
  // ============================================================
  makeSeedRule({
    stable_id: "REG-UK-002",
    title: "GB Type-Approval (Road Vehicles (Approval) Regulations 2020)",
    short_label: "GB Type-Approval (GBTA)",
    legal_family: "non_eu_market",
    jurisdiction: "UK",
    jurisdiction_level: "NON_EU_MARKET",
    framework_group: ["MN"],
    sources: [
      {
        label: "GB type-approval secondary legislation",
        source_family: "Other official" as const,
        reference: "Road Vehicles (Approval) Regulations 2020 (SI 2020/818) [verify]",
        official_url: "https://www.legislation.gov.uk/uksi/2020/818/contents/made",
        oj_reference: null,
        authoritative_reference: "SI 2020/818 [verify]",
        last_verified_on: null,
      },
      {
        label: "VCA Vehicle Type Approval guidance",
        source_family: "Other official" as const,
        reference: "Vehicle Certification Agency — GB type-approval guidance",
        official_url: "https://www.vehicle-certification-agency.gov.uk/vehicle-type-approval/",
        oj_reference: null,
        authoritative_reference: null,
        last_verified_on: null,
      },
    ],
    lifecycle_state: "SEED_UNVERIFIED",
    trigger_logic: {
      mode: "declarative",
      match_mode: "all",
      conditions: [
        { field: "targetCountries", operator: "includes", value: "UK" },
      ],
      fallback_if_missing: "not_applicable",
    },
    temporal: {
      entry_into_force: "2021-01-01",
      applies_to_new_types_from: null,
      applies_to_all_new_vehicles_from: null,
      applies_to_first_registration_from: null,
      applies_from_generic: "2021-01-01",
      effective_to: null,
      small_volume_derogation_until: null,
      notes:
        "EU-TA provisional recognition extended through 2028 per DfT guidance [verify current horizon]. Post-Brexit GB divergence from EU type-approval framework is gradual — VCA is GB approval authority.",
    },
    obligation_text:
      "Vehicles placed on the Great Britain (England/Wales/Scotland) market after 1 January 2021 require GB type-approval per SI 2020/818. Provisional recognition of EU type-approval is extended through 2028, enabling OEMs with existing EU TA to sell into GB without duplicate testing for that window [verify]. VCA (Vehicle Certification Agency) is the approval authority. Separate from Northern Ireland, which continues under EU WVTA per the Windsor Framework (REG-UK-011).",
    evidence_tasks: [
      "GB type-approval application package to VCA",
      "Liaison with VCA on provisional EU-TA recognition procedure",
      "CoC adaptation / labelling for GB market",
      "GB-specific dealer and importer setup",
      "Regulatory watch on post-2028 EU-TA recognition horizon",
    ],
    owner_hint: "homologation",
    planning_lead_time_months: 12,
    manual_review_reason:
      "SI 2020/818 citation and provisional EU-TA recognition horizon (currently through 2028) [verify].",
    related_rules: [
      { rule_id: "REG-TA-001", relation: "complements" },
      { rule_id: "REG-UK-011", relation: "complements" },
    ],
    ui_package: "market_access",
    process_stage: "type_approval",
    content_provenance: {
      source_type: "national_gazette",
      retrieved_at: "2026-04-20",
      human_reviewer: null,
    },
  }),

  makeSeedRule({
    stable_id: "REG-UK-003",
    title: "UK — DVLA Vehicle Registration (V5C)",
    short_label: "UK DVLA V5C",
    legal_family: "non_eu_market",
    jurisdiction: "UK",
    jurisdiction_level: "NON_EU_MARKET",
    framework_group: ["MN", "L", "O"],
    sources: [
      {
        label: "Primary Act — Vehicle Excise and Registration Act 1994",
        source_family: "UK Parliament" as const,
        reference: "Vehicle Excise and Registration Act 1994 (c. 22)",
        official_url: "https://www.legislation.gov.uk/ukpga/1994/22/contents",
        oj_reference: null,
        authoritative_reference: "VERA 1994 c.22",
        last_verified_on: null,
      },
      {
        label: "Secondary legislation — registration regulations",
        source_family: "Other official" as const,
        reference: "Road Vehicles (Registration and Licensing) Regulations 2002 (SI 2002/2742)",
        official_url: "https://www.legislation.gov.uk/uksi/2002/2742/contents/made",
        oj_reference: null,
        authoritative_reference: "SI 2002/2742",
        last_verified_on: null,
      },
    ],
    lifecycle_state: "SEED_UNVERIFIED",
    trigger_logic: {
      mode: "declarative",
      match_mode: "all",
      conditions: [
        { field: "targetCountries", operator: "includes", value: "UK" },
      ],
      fallback_if_missing: "not_applicable",
    },
    temporal: {
      entry_into_force: "2002-12-02",
      applies_to_new_types_from: null,
      applies_to_all_new_vehicles_from: null,
      applies_to_first_registration_from: "2002-12-02",
      applies_from_generic: "2002-12-02",
      effective_to: null,
      small_volume_derogation_until: null,
      notes:
        "SI 2002/2742 entry-into-force date [verify]. Regulations have been amended multiple times — consolidated current text on legislation.gov.uk [verify].",
    },
    obligation_text:
      "Every vehicle used on UK public roads must be registered with DVLA (Driver and Vehicle Licensing Agency). Dealer uses V55/4 (new vehicles) or V55/5 (used/imported) application forms; DVLA issues the V5C registration certificate to the keeper. Registration interlinks with Motor Insurance Database (MID) lookup and VED payment.",
    evidence_tasks: [
      "Dealer V55 application process documentation",
      "VIN / technical data package for DVLA submission",
      "Initial VED payment processing at registration",
      "V5C delivery to keeper coordination",
      "MID (Motor Insurance Database) lookup integration pre-registration",
    ],
    owner_hint: "regulatory_affairs",
    ui_package: "market_access",
    process_stage: "sop",
    content_provenance: {
      source_type: "national_gazette",
      retrieved_at: "2026-04-20",
      human_reviewer: null,
    },
  }),

  makeSeedRule({
    stable_id: "REG-UK-004",
    title: "UK — MoT Roadworthiness Test",
    short_label: "UK MoT",
    legal_family: "non_eu_market",
    jurisdiction: "UK",
    jurisdiction_level: "NON_EU_MARKET",
    framework_group: ["MN", "L"],
    sources: [
      {
        label: "Primary Act — Road Traffic Act 1988 §47",
        source_family: "UK Parliament" as const,
        reference: "Road Traffic Act 1988 (c. 52), section 47 (obligatory test certificates)",
        official_url: "https://www.legislation.gov.uk/ukpga/1988/52/section/47",
        oj_reference: null,
        authoritative_reference: "RTA 1988 s.47",
        last_verified_on: null,
      },
      {
        label: "Secondary — Motor Vehicle (Tests) Regulations 1981",
        source_family: "Other official" as const,
        reference: "Motor Vehicles (Tests) Regulations 1981 (SI 1981/1694)",
        official_url: "https://www.legislation.gov.uk/uksi/1981/1694/contents/made",
        oj_reference: null,
        authoritative_reference: "SI 1981/1694",
        last_verified_on: null,
      },
      {
        label: "Secondary — Construction and Use Regulations 1986",
        source_family: "Other official" as const,
        reference: "Road Vehicles (Construction and Use) Regulations 1986 (SI 1986/1078)",
        official_url: "https://www.legislation.gov.uk/uksi/1986/1078/contents/made",
        oj_reference: null,
        authoritative_reference: "SI 1986/1078",
        last_verified_on: null,
      },
    ],
    lifecycle_state: "SEED_UNVERIFIED",
    trigger_logic: {
      mode: "declarative",
      match_mode: "all",
      conditions: [
        { field: "targetCountries", operator: "includes", value: "UK" },
      ],
      fallback_if_missing: "not_applicable",
    },
    temporal: {
      entry_into_force: "1988-05-15",
      applies_to_new_types_from: null,
      applies_to_all_new_vehicles_from: null,
      applies_to_first_registration_from: null,
      applies_from_generic: "1988-05-15",
      effective_to: null,
      small_volume_derogation_until: null,
      notes:
        "First MoT at 3 years post first-registration, then annually for cars / light vehicles per gov.uk/getting-an-mot guidance. 4-year first-test proposal not enacted as of 2026 [verify]. DVSA is administrator.",
    },
    obligation_text:
      "Passenger cars (M1) and light vehicles registered in the UK must pass an annual MoT test from 3 years after first registration. BEVs are exempt from the emissions (tailpipe) element, but battery earth-leakage, structural, brake, steering, suspension, lighting, tyres, and visibility checks still apply. DVSA (Driver and Vehicle Standards Agency) administers.",
    evidence_tasks: [
      "Vehicle test-procedure submission to DVSA for type",
      "MoT tester training materials + high-voltage electrical safety procedure for BEV",
      "BEV-specific HV safety test specification",
      "First-MoT customer reminder system",
      "Parts-availability plan for common MoT-failure items",
    ],
    owner_hint: "aftersales",
    recurring_post_market_obligation: true,
    ui_package: "horizontal",
    process_stage: "post_market",
    content_provenance: {
      source_type: "national_gazette",
      retrieved_at: "2026-04-20",
      human_reviewer: null,
    },
  }),

  makeSeedRule({
    stable_id: "REG-UK-005",
    title: "UK — Vehicle Excise Duty (VED)",
    short_label: "UK VED",
    legal_family: "non_eu_market",
    jurisdiction: "UK",
    jurisdiction_level: "NON_EU_MARKET",
    framework_group: ["MN"],
    sources: [
      {
        label: "Primary framework Act",
        source_family: "UK Parliament" as const,
        reference: "Vehicle Excise and Registration Act 1994 (c. 22)",
        official_url: "https://www.legislation.gov.uk/ukpga/1994/22/contents",
        oj_reference: null,
        authoritative_reference: "VERA 1994 c.22",
        last_verified_on: null,
      },
      {
        label: "Finance Act 2022 (BEV VED change)",
        source_family: "UK Parliament" as const,
        reference: "Finance Act 2022 (c. 3) — amendments to VED BEV zero-rating [verify exact Act]",
        official_url: "https://www.legislation.gov.uk/ukpga/2022/3/contents",
        oj_reference: null,
        authoritative_reference: "Finance Act 2022 c.3 [verify]",
        last_verified_on: null,
      },
    ],
    lifecycle_state: "SEED_UNVERIFIED",
    trigger_logic: {
      mode: "declarative",
      match_mode: "all",
      conditions: [
        { field: "targetCountries", operator: "includes", value: "UK" },
      ],
      fallback_if_missing: "not_applicable",
    },
    temporal: {
      entry_into_force: "1994-07-05",
      applies_to_new_types_from: null,
      applies_to_all_new_vehicles_from: null,
      applies_to_first_registration_from: null,
      applies_from_generic: "1994-07-05",
      effective_to: null,
      small_volume_derogation_until: null,
      notes:
        "BEV VED zero-rating removed from 2025-04-01 per Finance Act 2022 [verify exact Act]. BEVs registered 1 April 2017 onwards become subject to standard rate plus the £40k+ expensive-car supplement from 2025-04-01 [verify figures].",
    },
    obligation_text:
      "Annual UK Vehicle Excise Duty is calculated per VERA 1994 based on CO₂ emissions, fuel type, and list price. From 1 April 2025, BEVs pay first-year £10, standard rate £195, plus £425 premium supplement for cars with list price over £40,000 [verify figures]. ICE vehicles follow the CO₂-banded scale. First-year VED is paid at registration.",
    evidence_tasks: [
      "CO₂ declaration feed for DVLA VED-band calculation",
      "First-year VED pricing communication to dealers",
      "Dealer VED-handling process at point of sale",
      "Annual VED-renewal reminder to keepers",
      "List-price declaration for £40k+ expensive-car supplement",
    ],
    owner_hint: "legal",
    manual_review_reason:
      "Finance Act citation for 1 April 2025 BEV VED change and current-year figures [verify].",
    ui_package: "horizontal",
    process_stage: "sop",
    content_provenance: {
      source_type: "national_gazette",
      retrieved_at: "2026-04-20",
      human_reviewer: null,
    },
  }),

  makeSeedRule({
    stable_id: "REG-UK-006",
    title: "UK — Compulsory Motor Insurance (RTA 1988 Part VI)",
    short_label: "UK Motor Insurance (RTA 1988)",
    legal_family: "non_eu_market",
    jurisdiction: "UK",
    jurisdiction_level: "NON_EU_MARKET",
    framework_group: ["MN", "L", "O", "AGRI"],
    sources: [
      {
        label: "Primary Act — Road Traffic Act 1988 Part VI",
        source_family: "UK Parliament" as const,
        reference: "Road Traffic Act 1988 (c. 52), sections 143 and 145 (Part VI)",
        official_url: "https://www.legislation.gov.uk/ukpga/1988/52/part/VI",
        oj_reference: null,
        authoritative_reference: "RTA 1988 ss.143, 145",
        last_verified_on: null,
      },
    ],
    lifecycle_state: "SEED_UNVERIFIED",
    trigger_logic: {
      mode: "declarative",
      match_mode: "all",
      conditions: [
        { field: "targetCountries", operator: "includes", value: "UK" },
      ],
      fallback_if_missing: "not_applicable",
    },
    temporal: {
      entry_into_force: "1988-05-15",
      applies_to_new_types_from: null,
      applies_to_all_new_vehicles_from: null,
      applies_to_first_registration_from: null,
      applies_from_generic: "1988-05-15",
      effective_to: null,
      small_volume_derogation_until: null,
      notes:
        "Minimum third-party property damage cover £1.2 million per accident [verify current statutory minimum]; personal injury cover unlimited. Motor Insurance Database (MID) lookup required pre-registration.",
    },
    obligation_text:
      "Every vehicle used on UK public roads must carry compulsory third-party liability insurance per RTA 1988 §§143, 145. Minimum property-damage cover £1.2 million per accident [verify]; personal injury cover unlimited. MID (Motor Insurance Database) lookup is required before DVLA registration. Coverage expectations for L3+ automated vehicles are supplemented by AV Act 2024 §46 [verify].",
    evidence_tasks: [
      "Insurance broker arrangements for direct-sales model",
      "MID pre-registration lookup integration",
      "Keeper insurance verification at handover",
      "AV-specific liability review for L3+ per AV Act 2024 §46 [verify]",
    ],
    owner_hint: "legal",
    related_rules: [
      { rule_id: "REG-UK-001", relation: "complements" },
    ],
    ui_package: "horizontal",
    process_stage: "sop",
    content_provenance: {
      source_type: "national_gazette",
      retrieved_at: "2026-04-20",
      human_reviewer: null,
    },
    notes: "Current statutory minimum property-damage cover figure [verify].",
  }),

  makeSeedRule({
    stable_id: "REG-UK-007",
    title: "UK — London Ultra-Low Emission Zone (ULEZ)",
    short_label: "UK London ULEZ",
    legal_family: "non_eu_market",
    jurisdiction: "UK",
    jurisdiction_level: "NON_EU_MARKET",
    framework_group: ["MN", "L"],
    sources: [
      {
        label: "Primary Act — GLA Act 1999",
        source_family: "UK Parliament" as const,
        reference: "Greater London Authority Act 1999 (c. 29)",
        official_url: "https://www.legislation.gov.uk/ukpga/1999/29/contents",
        oj_reference: null,
        authoritative_reference: "GLA Act 1999 c.29",
        last_verified_on: null,
      },
      {
        label: "Framework — Transport Act 2000",
        source_family: "UK Parliament" as const,
        reference: "Transport Act 2000 (c. 38)",
        official_url: "https://www.legislation.gov.uk/ukpga/2000/38/contents",
        oj_reference: null,
        authoritative_reference: "Transport Act 2000 c.38",
        last_verified_on: null,
      },
      {
        label: "TfL ULEZ scheme (TfL Charging Scheme Order + Variation) [verify exact Variation Order for 2023 expansion]",
        source_family: "Other official" as const,
        reference: "Transport for London — ULEZ Charging Scheme Order (as varied for 2023-08-29 London-wide expansion)",
        official_url: "https://tfl.gov.uk/modes/driving/ultra-low-emission-zone",
        oj_reference: null,
        authoritative_reference: null,
        last_verified_on: null,
      },
    ],
    lifecycle_state: "SEED_UNVERIFIED",
    trigger_logic: {
      mode: "declarative",
      match_mode: "all",
      conditions: [
        { field: "targetCountries", operator: "includes", value: "UK" },
      ],
      fallback_if_missing: "not_applicable",
    },
    temporal: {
      entry_into_force: "2019-04-08",
      applies_to_new_types_from: null,
      applies_to_all_new_vehicles_from: null,
      applies_to_first_registration_from: null,
      applies_from_generic: "2019-04-08",
      effective_to: null,
      small_volume_derogation_until: null,
      notes:
        "ULEZ introduced central London 2019-04-08; inner London expansion 2021-10-25; London-wide expansion 2023-08-29. Minimum standards: Euro 6 diesel / Euro 4 petrol; BEV exempt.",
    },
    obligation_text:
      "Vehicles operating in London ULEZ (all of Greater London from 29 August 2023) must meet Euro 6 diesel or Euro 4 petrol emission standards or pay £12.50 per day. BEVs are exempt. Non-payment penalty is £180 (reduced for prompt payment). Crosses over with Congestion Charge area for central London.",
    evidence_tasks: [
      "Emissions-class declaration on UK CoC / dealer data pack",
      "Dealer ULEZ-compliance messaging for customers",
      "Fleet ULEZ budget and operational planning",
      "Penalty-handling process for fleet / demo vehicles",
    ],
    owner_hint: "regulatory_affairs",
    recurring_post_market_obligation: true,
    related_rules: [
      { rule_id: "REG-UK-008", relation: "complements" },
    ],
    manual_review_reason:
      "Exact TfL ULEZ Charging Scheme Order / Variation Order citation for the 2023-08-29 London-wide expansion [verify].",
    ui_package: "horizontal",
    process_stage: "post_market",
    content_provenance: {
      source_type: "national_gazette",
      retrieved_at: "2026-04-20",
      human_reviewer: null,
    },
  }),

  makeSeedRule({
    stable_id: "REG-UK-008",
    title: "UK — Regional Clean Air Zones (England)",
    short_label: "UK Regional CAZ",
    legal_family: "non_eu_market",
    jurisdiction: "UK",
    jurisdiction_level: "NON_EU_MARKET",
    framework_group: ["MN"],
    sources: [
      {
        label: "Primary Act — Environment Act 2021",
        source_family: "UK Parliament" as const,
        reference: "Environment Act 2021 (c. 30)",
        official_url: "https://www.legislation.gov.uk/ukpga/2021/30/contents/enacted",
        oj_reference: null,
        authoritative_reference: "Environment Act 2021 c.30",
        last_verified_on: null,
      },
      {
        label: "Framework — Transport Act 2000 Part III",
        source_family: "UK Parliament" as const,
        reference: "Transport Act 2000 (c. 38), Part III (Road user charging and workplace parking levy)",
        official_url: "https://www.legislation.gov.uk/ukpga/2000/38/part/III",
        oj_reference: null,
        authoritative_reference: "Transport Act 2000 Part III",
        last_verified_on: null,
      },
      {
        label: "Local authority CAZ Charging Scheme Orders",
        source_family: "National legislation" as const,
        reference: "City-level CAZ Charging Scheme Orders (Bath, Birmingham, Portsmouth, Bristol, Bradford, Tyneside, Sheffield)",
        official_url: null,
        oj_reference: null,
        authoritative_reference: "Local authority orders under Transport Act 2000 Part III",
        last_verified_on: null,
      },
    ],
    lifecycle_state: "SEED_UNVERIFIED",
    trigger_logic: {
      mode: "declarative",
      match_mode: "all",
      conditions: [
        { field: "targetCountries", operator: "includes", value: "UK" },
      ],
      fallback_if_missing: "not_applicable",
    },
    temporal: {
      entry_into_force: "2021-03-15",
      applies_to_new_types_from: null,
      applies_to_all_new_vehicles_from: null,
      applies_to_first_registration_from: null,
      applies_from_generic: "2021-03-15",
      effective_to: null,
      small_volume_derogation_until: null,
      notes:
        "Active CAZ as of 2026: Bath 2021-03-15 (class C), Birmingham 2021-06-01 (class D), Portsmouth 2021-11-29 (class B), Bristol 2022-11-28 (class D) [verify], Bradford 2022-09-26 (class C) [verify], Tyneside 2023-01-30 (class C) [verify], Sheffield 2023-02-27 (class C) [verify]. Classes: A (taxis/PHVs), B (A + HGVs/buses), C (B + LGVs/vans), D (C + cars).",
    },
    obligation_text:
      "Non-compliant vehicles (below Euro 6 diesel / Euro 4 petrol) entering a Clean Air Zone pay a daily charge that varies by city and CAZ class. BEVs are exempt in all CAZs. Class determines which vehicle categories are charged: A (taxis/PHVs only), B (+HGVs/buses), C (+LGVs/vans), D (+private cars).",
    evidence_tasks: [
      "Euro-standard declaration for UK CoC / dealer pack",
      "City-by-city CAZ class lookup table",
      "Dealer and fleet customer communications",
      "BEV exemption confirmation in marketing material",
    ],
    owner_hint: "regulatory_affairs",
    recurring_post_market_obligation: true,
    related_rules: [
      { rule_id: "REG-UK-007", relation: "complements" },
      { rule_id: "REG-UK-009", relation: "complements" },
    ],
    manual_review_reason:
      "Bristol / Bradford / Tyneside / Sheffield CAZ launch dates [verify each local Charging Scheme Order].",
    ui_package: "horizontal",
    process_stage: "post_market",
    content_provenance: {
      source_type: "national_gazette",
      retrieved_at: "2026-04-20",
      human_reviewer: null,
    },
  }),

  makeSeedRule({
    stable_id: "REG-UK-009",
    title: "UK — Scotland Low Emission Zones (LEZ)",
    short_label: "UK Scotland LEZ",
    legal_family: "non_eu_market",
    jurisdiction: "UK",
    jurisdiction_level: "NON_EU_MARKET",
    framework_group: ["MN"],
    sources: [
      {
        label: "Primary Act — Transport (Scotland) Act 2019",
        source_family: "UK Parliament" as const,
        reference: "Transport (Scotland) Act 2019 (asp 17), Part 1 (Low Emission Zones)",
        official_url: "https://www.legislation.gov.uk/asp/2019/17/contents",
        oj_reference: null,
        authoritative_reference: "Transport (Scotland) Act 2019 asp 17 Part 1",
        last_verified_on: null,
      },
      {
        label: "Local authority LEZ Scheme Orders",
        source_family: "National legislation" as const,
        reference: "Glasgow / Edinburgh / Aberdeen / Dundee LEZ Scheme Orders",
        official_url: null,
        oj_reference: null,
        authoritative_reference: "Local authority orders under Transport (Scotland) Act 2019",
        last_verified_on: null,
      },
    ],
    lifecycle_state: "SEED_UNVERIFIED",
    trigger_logic: {
      mode: "declarative",
      match_mode: "all",
      conditions: [
        { field: "targetCountries", operator: "includes", value: "UK" },
      ],
      fallback_if_missing: "not_applicable",
    },
    temporal: {
      entry_into_force: "2023-06-01",
      applies_to_new_types_from: null,
      applies_to_all_new_vehicles_from: null,
      applies_to_first_registration_from: null,
      applies_from_generic: "2023-06-01",
      effective_to: null,
      small_volume_derogation_until: null,
      notes:
        "Enforcement dates: Glasgow 2023-06-01, Edinburgh 2024-06-01, Aberdeen 2024-06-01, Dundee 2024-05-30 [verify]. Minimum standards: Euro 6 diesel / Euro 4 petrol; BEV exempt. Scottish LEZ is statutorily distinct from English CAZ.",
    },
    obligation_text:
      "Non-compliant vehicles within a Scottish LEZ zone (Glasgow, Edinburgh, Aberdeen, Dundee) face a penalty charge on entry. BEVs are exempt. Scottish LEZ sits under Transport (Scotland) Act 2019 asp 17 — a distinct statutory regime from England's Clean Air Zones under the Environment Act 2021 / Transport Act 2000.",
    evidence_tasks: [
      "Scotland-specific fleet compliance plan",
      "Emissions-class documentation for Scottish dealerships",
      "BEV exemption documentation bundle",
      "Penalty-handling process for fleet / demo vehicles",
    ],
    owner_hint: "regulatory_affairs",
    recurring_post_market_obligation: true,
    related_rules: [
      { rule_id: "REG-UK-008", relation: "complements" },
    ],
    manual_review_reason:
      "Dundee LEZ enforcement start date [verify local Scheme Order].",
    ui_package: "horizontal",
    process_stage: "post_market",
    content_provenance: {
      source_type: "national_gazette",
      retrieved_at: "2026-04-20",
      human_reviewer: null,
    },
  }),

  makeSeedRule({
    stable_id: "REG-UK-010",
    title: "UK — ZEV Sales Mandate (Vehicle Emissions Trading Schemes)",
    short_label: "UK ZEV Mandate",
    legal_family: "non_eu_market",
    jurisdiction: "UK",
    jurisdiction_level: "NON_EU_MARKET",
    framework_group: ["MN"],
    sources: [
      {
        label: "Secondary legislation — Vehicle Emissions Trading Schemes Order",
        source_family: "Other official" as const,
        reference: "Vehicle Emissions Trading Schemes Order 2023 (SI 2023/1633) [verify]",
        official_url: "https://www.legislation.gov.uk/uksi/2023/1633/contents/made",
        oj_reference: null,
        authoritative_reference: "SI 2023/1633 [verify]",
        last_verified_on: null,
      },
      {
        label: "OZEV guidance",
        source_family: "Other official" as const,
        reference: "Office for Zero Emission Vehicles (OZEV) — ZEV mandate guidance",
        official_url: "https://www.gov.uk/government/collections/vehicle-emission-trading-schemes",
        oj_reference: null,
        authoritative_reference: null,
        last_verified_on: null,
      },
    ],
    lifecycle_state: "SEED_UNVERIFIED",
    trigger_logic: {
      mode: "declarative",
      match_mode: "all",
      conditions: [
        { field: "targetCountries", operator: "includes", value: "UK" },
        { field: "vehicleCategory", operator: "in", value: ["M1", "N1"] },
      ],
      fallback_if_missing: "not_applicable",
    },
    temporal: {
      entry_into_force: "2024-01-01",
      applies_to_new_types_from: null,
      applies_to_all_new_vehicles_from: null,
      applies_to_first_registration_from: null,
      applies_from_generic: "2024-01-01",
      effective_to: null,
      small_volume_derogation_until: null,
      notes:
        "Car ZEV trajectory: 22% (2024) → 28% (2025) → 33% (2026) → 38% (2027) → 52% (2028) → 66% (2029) → 80% (2030) → 100% (2035) [verify — may have been amended following the 2025 government consultation]. Van trajectory separate: 10% (2024) phasing to 100% (2035) [verify]. Credit and debit trading between OEMs permits flexibility.",
    },
    obligation_text:
      "OEMs selling cars (M1) and vans (N1) in Great Britain must meet annual ZEV-share targets or buy credits from ZEV-surplus OEMs (or use reserved flexibilities such as borrowing and CO₂ banking). Full ZEV (100%) target applies from 2035. The scheme is administered via the Vehicle Emissions Trading Schemes Order [verify SI 2023/1633].",
    evidence_tasks: [
      "Annual ZEV sales forecast for GB market",
      "OZEV annual reporting submission",
      "ZEV credit-trading strategy and counterparty contracts",
      "ICE-to-BEV product-mix plan through 2035",
      "Regulatory watch on post-2025 trajectory amendments",
    ],
    owner_hint: "regulatory_affairs",
    planning_lead_time_months: 36,
    manual_review_reason:
      "SI 2023/1633 citation and post-2025 ZEV trajectory percentages [verify — 2025 government consultation may have revised the curve].",
    ui_package: "market_access",
    process_stage: "pre_ta",
    content_provenance: {
      source_type: "national_gazette",
      retrieved_at: "2026-04-20",
      human_reviewer: null,
    },
  }),

  makeSeedRule({
    stable_id: "REG-UK-011",
    title: "UK — Windsor Framework (Northern Ireland — continuing EU alignment)",
    short_label: "UK Windsor Framework NI",
    legal_family: "non_eu_market",
    jurisdiction: "UK",
    jurisdiction_level: "NON_EU_MARKET",
    framework_group: ["MN"],
    sources: [
      {
        label: "Windsor Framework political agreement",
        source_family: "Other official" as const,
        reference:
          "Windsor Framework (political agreement, 27 February 2023) — amending the Protocol on Ireland/Northern Ireland in the EU-UK Withdrawal Agreement",
        official_url: "https://www.gov.uk/government/publications/the-windsor-framework",
        oj_reference: null,
        authoritative_reference: "Windsor Framework (2023-02-27)",
        last_verified_on: null,
      },
      {
        label: "EU-UK Withdrawal Agreement — Protocol on Ireland/Northern Ireland, Annex 2",
        source_family: "Other official" as const,
        reference:
          "Protocol on Ireland/Northern Ireland, Annex 2 (list of EU acts continuing in NI, incl. Reg (EU) 2018/858, Reg (EU) 2019/2144, UNECE R155/R156/R157)",
        official_url: "https://www.gov.uk/government/publications/agreement-on-the-withdrawal-of-the-united-kingdom-from-the-european-union",
        oj_reference: null,
        authoritative_reference: "Protocol on Ireland/NI Annex 2",
        last_verified_on: null,
      },
    ],
    lifecycle_state: "DRAFT",
    trigger_logic: {
      mode: "declarative",
      match_mode: "all",
      conditions: [
        { field: "targetCountries", operator: "includes", value: "UK" },
        { field: "dataFlags", operator: "includes", value: "targets_ni" },
      ],
      fallback_if_missing: "unknown",
    },
    temporal: {
      entry_into_force: "2023-02-27",
      applies_to_new_types_from: null,
      applies_to_all_new_vehicles_from: null,
      applies_to_first_registration_from: null,
      applies_from_generic: "2023-02-27",
      effective_to: null,
      small_volume_derogation_until: null,
      notes:
        "Windsor Framework announced 27 February 2023. Annex 2 of the Protocol on Ireland/Northern Ireland lists EU automotive acts that continue to apply in NI, including Regulation (EU) 2018/858 (WVTA), Regulation (EU) 2019/2144 (GSR2), and UNECE R155/R156/R157.",
    },
    obligation_text:
      "Vehicles placed on the Northern Ireland market must meet EU type-approval requirements (not GB-only approval under SI 2020/818). OEMs targeting NI therefore need to maintain full EU type-approval. Vehicles moving from GB to NI may require additional checks depending on qualifying-goods status under the framework.",
    evidence_tasks: [
      "Maintain EU type-approval for NI market access",
      "NI-specific distributor / authorised representative arrangement",
      "Annex 2 regulatory watch for newly added / removed EU acts",
      "GB-to-NI goods movement documentation (qualifying-goods status)",
    ],
    owner_hint: "regulatory_affairs",
    manual_review_reason:
      "Windsor Framework operational detail is implemented through a rolling series of UK and EU SIs from 2024 onwards [verify current consolidated guidance before promotion].",
    related_rules: [
      { rule_id: "REG-TA-001", relation: "requires" },
    ],
    ui_package: "market_access",
    process_stage: "pre_ta",
    content_provenance: {
      source_type: "national_gazette",
      retrieved_at: "2026-04-20",
      human_reviewer: null,
    },
  }),

  makeSeedRule({
    stable_id: "REG-UK-012",
    title: "UK — UK GDPR and Data Protection Act 2018",
    short_label: "UK GDPR / DPA 2018",
    legal_family: "non_eu_market",
    jurisdiction: "UK",
    jurisdiction_level: "NON_EU_MARKET",
    framework_group: ["MN", "L", "O", "AGRI"],
    sources: [
      {
        label: "Primary Act — Data Protection Act 2018",
        source_family: "UK Parliament" as const,
        reference: "Data Protection Act 2018 (c. 12)",
        official_url: "https://www.legislation.gov.uk/ukpga/2018/12/contents/enacted",
        oj_reference: null,
        authoritative_reference: "DPA 2018 c.12",
        last_verified_on: null,
      },
      {
        label: "Retained EU law — UK GDPR",
        source_family: "Other official" as const,
        reference:
          "Regulation (EU) 2016/679 as retained (UK GDPR) + Data Protection, Privacy and Electronic Communications (Amendments etc) (EU Exit) Regulations 2019 (SI 2019/419) [verify]",
        official_url: "https://www.legislation.gov.uk/uksi/2019/419/contents/made",
        oj_reference: null,
        authoritative_reference: "SI 2019/419 [verify]",
        last_verified_on: null,
      },
    ],
    lifecycle_state: "SEED_UNVERIFIED",
    trigger_logic: {
      mode: "declarative",
      match_mode: "all",
      conditions: [
        { field: "targetCountries", operator: "includes", value: "UK" },
        { field: "hasConnectedServices", operator: "is_true", value: true },
      ],
      fallback_if_missing: "unknown",
    },
    temporal: {
      entry_into_force: "2018-05-25",
      applies_to_new_types_from: null,
      applies_to_all_new_vehicles_from: null,
      applies_to_first_registration_from: null,
      applies_from_generic: "2018-05-25",
      effective_to: null,
      small_volume_derogation_until: null,
      notes:
        "DPA 2018 in force 2018-05-25; UK GDPR is a distinct retained instrument from 2021-01-01 post-Brexit transition. Data (Use and Access) Bill progressing through Parliament 2025-2026 [verify — successor to the lapsed DPDI Bill]. ICO (Information Commissioner's Office) is the supervisory authority.",
    },
    obligation_text:
      "Connected vehicles targeting the UK market and processing personal data of UK data subjects must comply with UK GDPR (retained Regulation (EU) 2016/679 as modified by the Data Protection Act 2018). ICO oversight. UK-specific divergences include subject access request procedures and the interpretation of the legitimate-interests basis. Connected vehicles virtually always process UK data subjects' personal data via telematics, mobile app, or remote control; this rule gates on hasConnectedServices as the practical signal. Vehicles processing UK personal data without connected services (e.g., offline in-cabin biometric capture retained on the vehicle) should verify UK GDPR applicability separately.",
    evidence_tasks: [
      "UK-specific privacy notice (distinct from EU GDPR notice)",
      "DPIA scoped to UK market",
      "ICO liaison / representative appointment (if controller outside UK)",
      "International transfer mechanism for data leaving UK (UK IDTA / UK Addendum to EU SCCs)",
      "Data-subject rights handling process aligned to UK GDPR",
    ],
    owner_hint: "privacy_data_protection",
    related_rules: [
      { rule_id: "REG-PV-001", relation: "complements" },
    ],
    manual_review_reason:
      "SI 2019/419 (UK GDPR exit regs) citation and status of the Data (Use and Access) Bill [verify].",
    ui_package: "horizontal",
    process_stage: "post_market",
    content_provenance: {
      source_type: "national_gazette",
      retrieved_at: "2026-04-20",
      human_reviewer: null,
    },
    notes:
      "Trigger gates on hasConnectedServices (plus UK target) as a practical proxy for UK data-subject personal-data processing; engine does not support nested OR expressions so processesPersonalData is not separately evaluated here. Offline personal-data processing (e.g., on-vehicle biometric capture with no cloud link) must be audited separately for UK GDPR applicability. Pattern differs from REG-PV-001 (GDPR), which uses match_mode: \"any\" across both data-processing flags without a country gate because GDPR applies market-wide in the EU.",
  }),

  makeSeedRule({
    stable_id: "REG-UK-013",
    title: "UK — Public Charge Point Regulations 2023",
    short_label: "UK Public Charge Point Regs",
    legal_family: "non_eu_market",
    jurisdiction: "UK",
    jurisdiction_level: "NON_EU_MARKET",
    framework_group: ["MN", "L"],
    sources: [
      {
        label: "Secondary legislation — Public Charge Point Regulations 2023",
        source_family: "Other official" as const,
        reference: "Public Charge Point Regulations 2023 (SI 2023/1168) [verify]",
        official_url: "https://www.legislation.gov.uk/uksi/2023/1168/contents/made",
        oj_reference: null,
        authoritative_reference: "SI 2023/1168 [verify]",
        last_verified_on: null,
      },
      {
        label: "Primary Act — Automated and Electric Vehicles Act 2018",
        source_family: "UK Parliament" as const,
        reference: "Automated and Electric Vehicles Act 2018 (c. 18)",
        official_url: "https://www.legislation.gov.uk/ukpga/2018/18/contents",
        oj_reference: null,
        authoritative_reference: "AEVA 2018 c.18",
        last_verified_on: null,
      },
    ],
    lifecycle_state: "DRAFT",
    trigger_logic: {
      mode: "declarative",
      match_mode: "all",
      conditions: [
        { field: "targetCountries", operator: "includes", value: "UK" },
        {
          field: "readiness.offersPublicChargingInfra",
          operator: "is_true",
          value: true,
        },
      ],
      fallback_if_missing: "not_applicable",
    },
    temporal: {
      entry_into_force: "2023-11-24",
      applies_to_new_types_from: null,
      applies_to_all_new_vehicles_from: null,
      applies_to_first_registration_from: null,
      applies_from_generic: "2023-11-24",
      effective_to: null,
      small_volume_derogation_until: null,
      notes:
        "Contactless payment on new chargers ≥8 kW from 2024-11-24 [verify]; on existing chargers ≥50 kW from 2025-11-24 [verify]. 99% reliability target applies to rapid (≥50 kW) networks. Regulator: OZEV / DfT.",
    },
    obligation_text:
      "OEMs (or their subsidiaries) operating public EV charging networks in the UK must comply with the Public Charge Point Regulations 2023: contactless payment on new ≥8 kW chargers from 2024-11-24 [verify] and existing ≥50 kW chargers from 2025-11-24 [verify]; pricing transparency in pence-per-kWh; 99% reliability for rapid (≥50 kW) networks; roaming access via payment intermediaries; 24/7 helpline. Vehicle-only OEMs without charging infrastructure are not directly in scope.",
    evidence_tasks: [
      "Contactless payment integration on charger fleet",
      "Uptime monitoring dashboard with 99% SLA tracking",
      "Roaming agreement with mobility service providers (MSPs)",
      "24/7 customer helpline standing up",
      "Pricing-display audit across charger estate",
    ],
    owner_hint: "connected_services",
    manual_review_reason:
      "SI 2023/1168 citation and contactless-compliance go-live dates (2024-11-24 new / 2025-11-24 existing) [verify].",
    ui_package: "market_access",
    process_stage: "post_market",
    content_provenance: {
      source_type: "national_gazette",
      retrieved_at: "2026-04-20",
      human_reviewer: null,
    },
  }),
];
