import { makeSeedRule, makeSource } from "@/registry/seed/shared";

export const vehicleApprovalRules = [
  makeSeedRule({
    stable_id: "REG-TA-001",
    title: "EU Whole Vehicle Type-Approval Framework",
    short_label: "WVTA (2018/858)",
    legal_family: "vehicle_approval",
    jurisdiction: "EU",
    jurisdiction_level: "EU",
    framework_group: ["MN", "O"],
    sources: [
      {
        label: "Framework regulation",
        source_family: "EUR-Lex",
        reference: "Regulation (EU) 2018/858",
        official_url: "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=celex%3A32018R0858",
        oj_reference: "OJ L 151, 14.6.2018",
        last_verified_on: "2026-04-16",
      },
    ],
    lifecycle_state: "ACTIVE",
    trigger_logic: {
      mode: "declarative",
      match_mode: "any",
      conditions: [{ field: "frameworkGroup", operator: "in", value: ["MN", "O"] }],
      fallback_if_missing: "unknown",
    },
    temporal: {
      entry_into_force: "2018-09-01",
      applies_to_new_types_from: "2020-09-01",
      applies_to_all_new_vehicles_from: "2022-09-01",
      applies_to_first_registration_from: null,
      applies_from_generic: null,
      effective_to: null,
      small_volume_derogation_until: null,
      notes: null,
    },
    obligation_text:
      "Motor vehicles (M, N) and their trailers (O) placed on the EU market require whole vehicle type-approval under this framework regulation.",
    evidence_tasks: [
      "Type-approval application",
      "Technical documentation package",
      "Certificate of Conformity (CoC)",
      "Test reports from designated technical service",
    ],
    owner_hint: "homologation",
    planning_lead_time_months: 24,
    manual_review_required: true,
    manual_review_reason: "EUR-Lex URL verification pending at implementation.",
    ui_package: "wvta_core",
    process_stage: "type_approval",
  }),
  makeSeedRule({
    stable_id: "REG-TA-002",
    title: "L-category Vehicle Type-Approval Framework",
    short_label: "L-cat (168/2013)",
    legal_family: "vehicle_approval",
    jurisdiction: "EU",
    jurisdiction_level: "EU",
    framework_group: ["L"],
    sources: [
      {
        label: "Framework regulation",
        source_family: "EUR-Lex" as const,
        reference: "Regulation (EU) No 168/2013 on the approval and market surveillance of two- or three-wheel vehicles and quadricycles",
        official_url: "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX%3A32013R0168",
        oj_reference: "OJ L 60, 2.3.2013",
        authoritative_reference: "CELEX:32013R0168",
        last_verified_on: "2026-04-24",
      },
    ],
    lifecycle_state: "ACTIVE",
    promoted_on: "2026-04-24",
    promoted_by: "phase-m.0.1",
    trigger_logic: {
      mode: "declarative",
      match_mode: "all",
      conditions: [{ field: "frameworkGroup", operator: "eq", value: "L" }],
      fallback_if_missing: "unknown",
    },
    temporal: {
      entry_into_force: "2013-03-22",
      applies_to_new_types_from: "2016-01-01",
      applies_to_all_new_vehicles_from: null,
      applies_to_first_registration_from: null,
      applies_from_generic: null,
      effective_to: null,
      small_volume_derogation_until: null,
      notes: null,
    },
    obligation_text:
      "L-category vehicles (mopeds, motorcycles, tricycles, quadricycles) require type-approval under Regulation (EU) No 168/2013, a framework separate from the M/N/O type-approval regime of Regulation (EU) 2018/858.",
    owner_hint: "homologation",
    ui_package: "wvta_core",
    process_stage: "type_approval",
    content_provenance: {
      source_type: "eur_lex",
      retrieved_at: "2026-04-24",
      human_reviewer: "yanhao",
    },
  }),
  makeSeedRule({
    stable_id: "REG-TA-003",
    title: "Agricultural and Forestry Vehicle Type-Approval Framework",
    short_label: "AGRI (167/2013)",
    legal_family: "vehicle_approval",
    jurisdiction: "EU",
    jurisdiction_level: "EU",
    framework_group: ["AGRI"],
    sources: [
      makeSource(
        "Framework regulation",
        "EUR-Lex",
        "Regulation (EU) No 167/2013",
      ),
    ],
    lifecycle_state: "PLACEHOLDER",
    trigger_logic: {
      mode: "declarative",
      match_mode: "all",
      conditions: [],
      fallback_if_missing: "unknown",
    },
    obligation_text: "PLACEHOLDER — details not yet authored.",
    owner_hint: "homologation",
    ui_package: "wvta_core",
    process_stage: "type_approval",
  }),
];
