import { makeSeedRule, makeSource } from "@/registry/seed/shared";

export const vehicleApprovalRules = [
  makeSeedRule({
    stable_id: "REG-TA-001",
    title: "EU Whole Vehicle Type-Approval Framework",
    short_label: "WVTA (2018/858)",
    legal_family: "vehicle_approval",
    jurisdiction: "EU",
    jurisdiction_level: "EU",
    framework_group: ["MN", "O"],
    sources: [
      {
        label: "Framework regulation",
        source_family: "EUR-Lex",
        reference: "Regulation (EU) 2018/858",
        official_url: "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=celex%3A32018R0858",
        oj_reference: "OJ L 151, 14.6.2018",
        last_verified_on: "2026-04-16",
      },
    ],
    lifecycle_state: "ACTIVE",
    trigger_logic: {
      mode: "declarative",
      match_mode: "any",
      conditions: [{ field: "frameworkGroup", operator: "in", value: ["MN", "O"] }],
      fallback_if_missing: "unknown",
    },
    temporal: {
      entry_into_force: "2018-09-01",
      applies_to_new_types_from: "2020-09-01",
      applies_to_all_new_vehicles_from: "2022-09-01",
      applies_to_first_registration_from: null,
      applies_from_generic: null,
      effective_to: null,
      small_volume_derogation_until: null,
      notes: null,
    },
    obligation_text:
      "Motor vehicles (M, N) and their trailers (O) placed on the EU market require whole vehicle type-approval under this framework regulation.",
    evidence_tasks: [
      "Type-approval application",
      "Technical documentation package",
      "Certificate of Conformity (CoC)",
      "Test reports from designated technical service",
    ],
    owner_hint: "homologation",
    planning_lead_time_months: 24,
    manual_review_required: true,
    manual_review_reason: "EUR-Lex URL verification pending at implementation.",
    ui_package: "wvta_core",
    process_stage: "type_approval",
  }),
  makeSeedRule({
    stable_id: "REG-TA-002",
    title: "L-category Vehicle Type-Approval Framework",
    short_label: "L-cat (168/2013)",
    legal_family: "vehicle_approval",
    jurisdiction: "EU",
    jurisdiction_level: "EU",
    framework_group: ["L"],
    sources: [
      {
        label: "Framework regulation",
        source_family: "EUR-Lex" as const,
        reference: "Regulation (EU) No 168/2013 on the approval and market surveillance of two- or three-wheel vehicles and quadricycles",
        official_url: "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX%3A32013R0168",
        oj_reference: "OJ L 60, 2.3.2013",
        authoritative_reference: "CELEX:32013R0168",
        last_verified_on: "2026-04-24",
      },
    ],
    lifecycle_state: "ACTIVE",
    promoted_on: "2026-04-24",
    promoted_by: "phase-m.0.1",
    trigger_logic: {
      mode: "declarative",
      match_mode: "all",
      conditions: [{ field: "frameworkGroup", operator: "eq", value: "L" }],
      fallback_if_missing: "unknown",
    },
    temporal: {
      entry_into_force: "2013-03-22",
      applies_to_new_types_from: "2016-01-01",
      applies_to_all_new_vehicles_from: null,
      applies_to_first_registration_from: null,
      applies_from_generic: null,
      effective_to: null,
      small_volume_derogation_until: null,
      notes: null,
    },
    obligation_text:
      "L-category vehicles (mopeds, motorcycles, tricycles, quadricycles) require type-approval under Regulation (EU) No 168/2013, a framework separate from the M/N/O type-approval regime of Regulation (EU) 2018/858.",
    owner_hint: "homologation",
    ui_package: "wvta_core",
    process_stage: "type_approval",
    content_provenance: {
      source_type: "eur_lex",
      retrieved_at: "2026-04-24",
      human_reviewer: "yanhao",
    },
  }),
  makeSeedRule({
    stable_id: "REG-TA-003",
    title: "Agricultural and Forestry Vehicle Type-Approval Framework",
    short_label: "AGRI (167/2013)",
    legal_family: "vehicle_approval",
    jurisdiction: "EU",
    jurisdiction_level: "EU",
    framework_group: ["AGRI"],
    sources: [
      makeSource(
        "Framework regulation",
        "EUR-Lex",
        "Regulation (EU) No 167/2013",
      ),
    ],
    lifecycle_state: "PLACEHOLDER",
    trigger_logic: {
      mode: "declarative",
      match_mode: "all",
      conditions: [],
      fallback_if_missing: "unknown",
    },
    obligation_text: "PLACEHOLDER — details not yet authored.",
    owner_hint: "homologation",
    ui_package: "wvta_core",
    process_stage: "type_approval",
  }),

  // Phase M.1 — WVTA Annex II master implementing act (Impl Reg 2021/535)
  makeSeedRule({
    stable_id: "REG-TA-004",
    title:
      "WVTA Annex II master implementing act — uniform procedures and technical specifications",
    short_label: "WVTA Annex II (2021/535)",
    legal_family: "vehicle_approval",
    jurisdiction: "EU",
    jurisdiction_level: "EU",
    framework_group: ["MN", "O"],
    sources: [
      {
        label: "Implementing regulation",
        source_family: "EUR-Lex" as const,
        reference:
          "Commission Implementing Regulation (EU) 2021/535 laying down rules for the application of Regulation (EU) 2019/2144 as regards uniform procedures and technical specifications for the type-approval of vehicles, and of systems, components and separate technical units intended for such vehicles, as regards their general construction characteristics and safety",
        official_url: "https://eur-lex.europa.eu/eli/reg_impl/2021/535/oj",
        oj_reference: "OJ L 117, 6.4.2021, p. 1",
        authoritative_reference: "CELEX:32021R0535",
        last_verified_on: "2026-04-24",
      },
    ],
    lifecycle_state: "ACTIVE",
    promoted_on: "2026-04-24",
    promoted_by: "phase-m.1",
    trigger_logic: {
      mode: "declarative",
      match_mode: "any",
      conditions: [
        {
          field: "frameworkGroup",
          operator: "in",
          value: ["MN", "O"],
          label: "Framework group is M/N or O",
        },
      ],
      fallback_if_missing: "unknown",
    },
    temporal: {
      entry_into_force: "2021-04-26",
      applies_to_new_types_from: "2022-07-06",
      applies_to_all_new_vehicles_from: "2024-07-07",
      applies_to_first_registration_from: null,
      applies_from_generic: null,
      effective_to: null,
      small_volume_derogation_until: null,
      notes:
        "Master implementing act for GSR2 Annex II — covers general construction characteristics (VIN check-digit, registration-plate space, rear-view devices, speed limiter, tyre installation, fuel-tank installation, spray-suppression, overall dimensions and masses, etc.).",
    },
    obligation_text:
      "Vehicles of categories M, N and O must comply with the uniform procedures and technical specifications set out in Impl Reg (EU) 2021/535 implementing GSR2 (2019/2144). Covers systems, components and separate technical units listed in Annex II (general construction characteristics and safety features).",
    evidence_tasks: [
      "Type-approval test reports for each Impl Reg 2021/535 Annex II system",
      "VIN structure / check-digit compliance evidence",
      "Overall dimensions, masses and towing capacity conformity",
      "Front and rear registration-plate mounting space verification",
    ],
    owner_hint: "homologation",
    planning_lead_time_months: 18,
    ui_package: "wvta_core",
    process_stage: "type_approval",
    content_provenance: {
      source_type: "eur_lex",
      retrieved_at: "2026-04-24",
      human_reviewer: "yanhao",
    },
    related_rules: [
      { rule_id: "REG-TA-001", relation: "requires" },
      { rule_id: "REG-GSR-001", relation: "complements" },
    ],
  }),
];
