import type { VehicleConfig } from "@/config/schema";

export const defaultVehicleConfig: VehicleConfig = {
  projectName: "",
  vehicleCode: "",
  targetCountries: [],
  sopDate: null,
  firstRegistrationDate: null,
  consumerOrFleet: "consumer",
  salesModel: "dealer",
  frameworkGroup: null,
  vehicleCategory: null,
  bodyType: "",
  approvalType: "new_type",
  steeringPosition: "LHD",
  completionState: "complete",
  powertrain: null,
  batteryCapacityBand: null,
  chargingCapability: {
    ac: false,
    dc: false,
    bidirectional: false,
  },
  automationLevel: "none",
  adasFeatures: [],
  parkingAutomation: false,
  motorwayAssistant: false,
  systemInitiatedLaneChange: false,
  connectivity: [],
  dataFlags: [],
  aiLevel: "none",
  aiInventoryExists: false,
  braking: undefined,
  steering: undefined,
  cabin: undefined,
  lighting: undefined,
  fuel: undefined,
  hmi: undefined,
  readiness: {
    csmsAvailable: false,
    sumsAvailable: false,
    dpiaCompleted: false,
    technicalDocStarted: false,
    evidenceOwnerAssigned: false,
    registrationAssumptionsKnown: false,
  },
};
