#!/usr/bin/env node
/**
 * Phase J.4 — Verification Backlog Generator
 *
 * Reads `rawSeedRules` from the registry, filters to rules in lifecycle
 * states awaiting human source verification (SEED_UNVERIFIED / DRAFT /
 * PLACEHOLDER), groups them by jurisdiction, and emits a markdown backlog
 * used by reviewers to drive the verification queue.
 *
 * Usage:
 *   npx tsx scripts/emit-verification-backlog.ts > docs/phase-j/verification-backlog.md
 *   # or the convenience npm script:
 *   npm run verification-backlog
 *
 * The script is pure: no network calls, no writes (stdout only).
 * Promotion itself is a separate human-review workstream per
 * docs/source-policy.md — this script only produces the list.
 *
 * © Yanhao FU
 */

import { rawSeedRules } from "@/registry/seed";
import type { Rule } from "@/registry/schema";

type UrlStatus = "ok" | "missing" | "verify-marked";
type EffortEstimate = "S" | "M" | "L";

interface BacklogEntry {
  stable_id: string;
  title: string;
  jurisdiction: string;
  legal_family: string;
  lifecycle_state: string;
  official_url_status: UrlStatus;
  has_oj_reference: boolean;
  has_last_verified_on: boolean;
  recommended_reviewer: string;
  effort_estimate: EffortEstimate;
}

const PENDING_STATES = new Set(["SEED_UNVERIFIED", "DRAFT", "PLACEHOLDER"]);

function classifyUrlStatus(rule: Rule): UrlStatus {
  const url = rule.sources[0]?.official_url;
  if (url === null || url === undefined) return "missing";
  if (url.includes("[verify]")) return "verify-marked";
  return "ok";
}

function estimateEffort(rule: Rule): EffortEstimate {
  // Larger effort for domains with multi-instrument / delegated-act stacks.
  if (rule.legal_family === "materials_chemicals") return "L";
  if (
    rule.legal_family === "ai_governance" ||
    rule.legal_family === "emissions_co2"
  ) {
    return "M";
  }
  return "S";
}

function toEntry(rule: Rule): BacklogEntry {
  return {
    stable_id: rule.stable_id,
    title: rule.title,
    jurisdiction: rule.jurisdiction,
    legal_family: rule.legal_family,
    lifecycle_state: rule.lifecycle_state,
    official_url_status: classifyUrlStatus(rule),
    has_oj_reference:
      rule.sources[0]?.oj_reference !== null &&
      rule.sources[0]?.oj_reference !== undefined,
    has_last_verified_on:
      rule.sources[0]?.last_verified_on !== null &&
      rule.sources[0]?.last_verified_on !== undefined,
    recommended_reviewer: rule.owner_hint,
    effort_estimate: estimateEffort(rule),
  };
}

function escapeCell(value: string): string {
  // Markdown table cells: escape pipe and collapse newlines.
  return value.replace(/\|/g, "\\|").replace(/\r?\n/g, " ");
}

function truncate(value: string, max: number): string {
  if (value.length <= max) return value;
  return value.slice(0, max - 1) + "…";
}

function main(): void {
  const pending = rawSeedRules.filter((r) =>
    PENDING_STATES.has(r.lifecycle_state),
  );

  const entries = pending.map(toEntry);

  const byLifecycle = entries.reduce<Record<string, number>>((acc, e) => {
    acc[e.lifecycle_state] = (acc[e.lifecycle_state] ?? 0) + 1;
    return acc;
  }, {});

  const byFamily = entries.reduce<Record<string, number>>((acc, e) => {
    acc[e.legal_family] = (acc[e.legal_family] ?? 0) + 1;
    return acc;
  }, {});

  const byEffort = entries.reduce<Record<EffortEstimate, number>>(
    (acc, e) => {
      acc[e.effort_estimate] = (acc[e.effort_estimate] ?? 0) + 1;
      return acc;
    },
    { S: 0, M: 0, L: 0 },
  );

  const byCountry = entries.reduce<Record<string, BacklogEntry[]>>(
    (acc, e) => {
      (acc[e.jurisdiction] ??= []).push(e);
      return acc;
    },
    {},
  );

  const today = new Date().toISOString().slice(0, 10);

  const out: string[] = [];
  out.push("# Phase J Verification Backlog");
  out.push("");
  out.push(
    "_Auto-generated by `scripts/emit-verification-backlog.ts`. Do not edit by hand — run `npm run verification-backlog` to regenerate._",
  );
  out.push("");
  out.push(`Generated: ${today}`);
  out.push("");
  out.push(`Total rules pending human verification: **${entries.length}**`);
  out.push("");
  out.push("## Summary");
  out.push("");
  out.push("### By lifecycle state");
  out.push("");
  out.push("| Lifecycle state | Count |");
  out.push("|---|---|");
  for (const [state, count] of Object.entries(byLifecycle).sort()) {
    out.push(`| ${state} | ${count} |`);
  }
  out.push("");
  out.push("### By legal family");
  out.push("");
  out.push("| Legal family | Count |");
  out.push("|---|---|");
  for (const [family, count] of Object.entries(byFamily).sort()) {
    out.push(`| ${family} | ${count} |`);
  }
  out.push("");
  out.push("### By effort estimate");
  out.push("");
  out.push("| Effort | Count | Notes |");
  out.push("|---|---|---|");
  out.push(`| S | ${byEffort.S} | Single-instrument rules (most seeds). |`);
  out.push(
    `| M | ${byEffort.M} | AI Act / Euro 7 — multiple implementing acts per rule. |`,
  );
  out.push(
    `| L | ${byEffort.L} | Battery / REACH / ELV — stacked delegated acts and phase-in schedules. |`,
  );
  out.push("");
  out.push("## How to read the per-country tables");
  out.push("");
  out.push("- **URL** — status of `sources[0].official_url`:");
  out.push("  - `ok` — non-null URL, not tagged `[verify]`.");
  out.push("  - `missing` — `null`. Reviewer must find an authoritative link.");
  out.push(
    "  - `verify-marked` — present but embedded `[verify]` marker; needs re-checking.",
  );
  out.push(
    "- **OJ** — whether `sources[0].oj_reference` is populated (Official Journal / national gazette citation).",
  );
  out.push(
    "- **verified** — whether `sources[0].last_verified_on` is populated. ACTIVE promotion requires this.",
  );
  out.push(
    "- **reviewer** — value of `owner_hint`; the suggested reviewer track.",
  );
  out.push(
    "- **effort** — S/M/L heuristic from legal family. Reviewer judgement overrides.",
  );
  out.push("");
  out.push("## Per-country tables");
  out.push("");

  const sortedCountries = Object.keys(byCountry).sort();
  for (const country of sortedCountries) {
    const rules = byCountry[country].slice().sort((a, b) =>
      a.stable_id.localeCompare(b.stable_id),
    );
    out.push(`### ${country} (${rules.length})`);
    out.push("");
    out.push(
      "| stable_id | title | lifecycle | URL | OJ | verified | reviewer | effort |",
    );
    out.push("|---|---|---|---|---|---|---|---|");
    for (const r of rules) {
      out.push(
        `| ${r.stable_id} | ${escapeCell(truncate(r.title, 60))} | ${r.lifecycle_state} | ${r.official_url_status} | ${r.has_oj_reference ? "yes" : "no"} | ${r.has_last_verified_on ? "yes" : "no"} | ${r.recommended_reviewer} | ${r.effort_estimate} |`,
      );
    }
    out.push("");
  }

  out.push("## Next step");
  out.push("");
  out.push(
    "See `docs/phase-j/README.md` for the per-rule human-verification flow (find authoritative source, populate `official_url` + `oj_reference` + `last_verified_on`, record reviewer in `content_provenance.human_reviewer`, add `promotionLog` entry, flip `lifecycle_state` to `ACTIVE`).",
  );
  out.push("");

  process.stdout.write(out.join("\n"));
}

main();
